// Generated from the preserved Java port by tools/TranslateCore.java.
#pragma once
#include "../java_compat.hpp"
namespace godog {
    class Vec3f;
    class Vec3d;
    class Mat3f;
    class Quaternionf;
    class UvCoord;
    class Vertex;
    class Camera;
    class ScalarFieldVertex;
    class IsoSurfaceIntersection;
    class SortableItem;
    class RenderPrimitive;
    class Triangle;
    class MeshObject;
    class TexturedTriangleRasterizer;
    class LineRasterizer;
    class RgbSurface;
    class IndexedSurface;
    class ObjectSortEntry;
    class DepthSorter;
    class ViewFrustum;
    class MarchingCubesTables;
    class MetaballMesh;
    class ParticleVertex;
    class ParticleCloudMesh;
    class RadialFlareMesh;
    class WireframeMesh;
    class BackdropMesh;
    class HeightFieldMesh;
    class TrackKeyframe;
    class SplineTrack;
    class SurfacePresenter;
    class RgbSurfacePresenter;
    class SceneRenderer;
    class AseSceneLoader;
    class IguMeshLoader;
    class Scene;
    class VehjeScene;
    class PaaScene;
    class TravScene;
    class EvilScene;
    class LinjanenScene;
    class ByteReaders;
    class Envelope;
    class EnvelopeCursor;
    class ModuleSample;
    class ModuleInstrument;
    class ModulePattern;
    class ModuleSequencer;
    class Mixable;
    class MixerBusListener;
    class ModuleVoice;
    class ModuleChannel;
    class MixerBus;
    class ModuleSong;
    class ModuleLoader;
    class MovieBitReader;
    class MovieBounds;
    class MovieTransform;
    class MovieColorTransform;
    class MovieCharacter;
    class QuadraticEdge;
    class MovieScanlineEdge;
    class MovieFillStyle;
    class MovieDisplayObject;
    class MovieFillSpan;
    class MovieShapeDecoder;
    class MovieBitmap;
    class MovieRasterizer;
    class MovieTimeline;
    class MovieSurfaceBridge;
    class MovieIntroScene;
    class GraphicsRoutine;
    class EndscreenRoutine;
    class SmoothedFrameTimer;
    class godog;
    class StartupTunerCanvas;
    class LegacyFullscreenWindow;
    class IndexedSurfacePresenter;
    struct Container;
    struct Font;
    class MoviePlayer;
    class MovieAudioClip;
    class MovieController;
    struct MAD;
    struct ScriptEventScheduler;
    struct SongPositionQueue;
    class DesktopDemoBase;
    class ImageMathSupport;
    class godog;
    class SoftwareImageSurface;
    class SoftwareImageSurface : public Object {
      public:
        int32_t width{}, height{};
        Ref<ColorModel> colorModel;
        Ref<ImageConsumer> consumer;
        SoftwareImageSurface(int32_t w, int32_t h) : width(w), height(h), consumer(make_ref<ImageConsumer>()) {}
        virtual void publishRegion(int32_t, int32_t, int32_t, int32_t) {}
        void setImageEnabled(bool) {}
    };
    class Vec3f : public Object {
      public:
        static Ref<Vec3f> MaJaKka_field;
        static Ref<Vec3f> maJaKka_field;
        static Ref<Vec3f> MAJaKka_field;
        static Ref<Vec3f> mAJaKka_field;
        float x{};
        float y{};
        float z{};
        Vec3f();
        Vec3f(Ref<Vec3f> kaajmma);
        Vec3f(float majaKka, float majaKka2, float mAjaKka);
        Vec3f(double n, double n2, double n3);
        virtual void MAJAkKA(Ref<Vec3f> kaajmma);
        virtual void mAJaKka(float majaKka, float majaKka2, float mAjaKka);
        virtual void MajAkKA(double n, double n2, double n3);
        virtual void mAJAKKA(float mAjaKka);
        virtual void mAjaKka(double n);
        virtual float MaJakKA(Ref<Vec3f> kaajmma);
        virtual float maJAKka();
        virtual float maJAKKA();
        virtual float MAJaKka();
        virtual float maJaKka();
        virtual float MAjAkKA();
        virtual void MAJAKKA();
        virtual void MaJaKka(Ref<Vec3f> kaajmma);
        virtual void MajAKKA(Ref<Vec3f> kaajmma);
        virtual void MajaKKA(float n, float n2, float n3);
        virtual void MAjakKA(float n, float n2, float n3);
        virtual void mAjakKA(float n);
        virtual void mAJaKKA(float n);
        virtual void MAJAKka(Ref<Vec3f> kaajmma);
        virtual void mAjAKKA(float n, float n2, float n3);
        virtual void MaJAkKA(Ref<Vec3f> kaajmma);
        virtual void MaJAKKA();
        virtual void majAKKA(float n);
        virtual void MajaKka(float n);
        virtual void majakKA(float n);
        virtual void majAkKA(Ref<Vec3f> kaajmma);
        virtual void MAJaKKA(float n, float n2, float n3);
        virtual Ref<Vec3f> mAjAkKA(Ref<Vec3f> kaajmma);
        virtual Ref<Vec3f> MAJakKA(Ref<Vec3f> kaajmma);
        virtual Ref<Vec3f> mAJakKA(float n, float n2, float n3);
        virtual Ref<Vec3f> MAjaKka(float n, float n2, float n3);
        virtual Ref<Vec3f> MAjAKKA();
        virtual Ref<Vec3f> MajakKA(float n);
        virtual Ref<Vec3f> MaJAKka(float n);
        virtual Ref<Vec3f> maJAkKA(Ref<Vec3f> kaajmma);
        virtual Ref<Vec3f> majaKka(Ref<Vec3f> kaajmma);
        virtual Ref<Vec3f> maJakKA();
        virtual Ref<Vec3f> mAjaKKA(float n);
        virtual Ref<Vec3f> MAjaKKA(float n);
        virtual Ref<Vec3f> majaKKA(float n);
        virtual Ref<Vec3f> maJaKKA(Ref<Vec3f> kaajmma);
        virtual Ref<Vec3f> mAJAkKA(float n, float n2, float n3);
        virtual String toString();
        static void initialize_static();
        virtual void releaseReferences();
    };
    class Vec3d : public Object {
      public:
        static Ref<Vec3d> mAjaKka;
        static Ref<Vec3d> MaJAKka;
        static Ref<Vec3d> maJAKka;
        static Ref<Vec3d> MAJAKka;
        double x{};
        double y{};
        double z{};
        Vec3d();
        Vec3d(Ref<Vec3d> mmjamma);
        Vec3d(double majaKka, double majAKka, double majAKka2);
        virtual void mAjAKKa(Ref<Vec3d> mmjamma);
        virtual void majaKKa(double majaKka, double majAKka, double majAKka2);
        virtual void maJakKa(double majAKka);
        virtual double mAjaKKa(Ref<Vec3d> mmjamma);
        virtual double MaJaKKa();
        virtual double MaJAKKa();
        virtual double MAJAkka();
        virtual double maJAkka();
        virtual double MaJAkka();
        virtual void MaJakka();
        virtual void maJakka(Ref<Vec3d> mmjamma);
        virtual void MAJaKKa(Ref<Vec3d> mmjamma);
        virtual void MAjAKKa(double n, double n2, double n3);
        virtual void mAJAkka(double n, double n2, double n3);
        virtual void Majakka(double n);
        virtual void MAJAKKa(double n);
        virtual void MajAkka(Ref<Vec3d> mmjamma);
        virtual void majAKka(double n, double n2, double n3);
        virtual void majAKKa(Ref<Vec3d> mmjamma);
        virtual void mAjAKka();
        virtual void MajAKka(double n);
        virtual void maJaKKa(double n);
        virtual void MAJakka(double n);
        virtual void MAjAKka(Ref<Vec3d> mmjamma);
        virtual void MajAKKa(double n, double n2, double n3);
        virtual Ref<Vec3d> maJAKKa(Ref<Vec3d> mmjamma);
        virtual Ref<Vec3d> mAjakka(Ref<Vec3d> mmjamma);
        virtual Ref<Vec3d> MAJakKa(double n, double n2, double n3);
        virtual Ref<Vec3d> MAjAkka(double n, double n2, double n3);
        virtual Ref<Vec3d> majakka();
        virtual Ref<Vec3d> MaJakKa(double n);
        virtual Ref<Vec3d> mAjAkka(double n);
        virtual Ref<Vec3d> majAkka(Ref<Vec3d> mmjamma);
        virtual Ref<Vec3d> mAJAKKa(Ref<Vec3d> mmjamma);
        virtual Ref<Vec3d> MAjakka();
        virtual Ref<Vec3d> MAjaKKa(double n);
        virtual Ref<Vec3d> MajaKKa(double n);
        virtual Ref<Vec3d> mAJaKKa(double n);
        virtual Ref<Vec3d> mAJAKka(Ref<Vec3d> mmjamma);
        virtual Ref<Vec3d> mAJakka(double n, double n2, double n3);
        virtual String toString();
        static void initialize_static();
        virtual void releaseReferences();
    };
    class Mat3f : public Object {
      public:
        float KaMAjaK{};
        float kaMAjaK{};
        float KAMAjaK{};
        float kAMAjaK{};
        float KamAjaK{};
        float kamAjaK{};
        float KAmAjaK{};
        float kAmAjaK{};
        float KaMaJAK_field{};
        Mat3f();
        Mat3f(Ref<Vec3f> kaajmma, Ref<Vec3f> kaajmma2, Ref<Vec3f> kaajmma3);
        Mat3f(Ref<Vec3f> kaajmma);
        Mat3f(Ref<Mat3f> kaaakka);
        virtual void KamajAK();
        virtual void kamAjAK(Ref<Vec3f> kaajmma, Ref<Vec3f> kaajmma2, Ref<Vec3f> kaajmma3);
        virtual void kamajAK(Ref<Vec3f> kaajmma);
        virtual void KamAjAK(float n, float n2, float n3);
        virtual void KamaJAK(Ref<Vec3f> kaajmma);
        virtual void KAMajAK(float kaMAjaK, float kaMAjaK2, float kamAjaK);
        virtual void KAMaJAK(Ref<Vec3f> kaajmma);
        virtual void kaMajAK(float kamAjaK, float kamAjaK2, float kamAjaK3);
        virtual void kaMaJAK(Ref<Vec3f> kaajmma);
        virtual void KaMajAK(float kAmAjaK, float kAmAjaK2, float kaMaJAK);
        virtual void KaMAjAK(Ref<Mat3f> kaaakka);
        virtual void kAMAjAK(Ref<Vec3f> kaajmma);
        virtual void kAMAJAK(Ref<Vec3f> kaajmma);
        virtual void kAMaJak(Ref<Vec3f> kaajmma);
        virtual Ref<Vec3f> KAMaJak();
        virtual Ref<Vec3f> kaMaJak();
        virtual Ref<Vec3f> kAmAjAK();
        virtual void KAmajAK(float n);
        virtual Ref<Mat3f> kAmajAK(float n);
        virtual void KAmAjAK(Ref<Vec3f> kaajmma);
        virtual Ref<Vec3f> kaMAjAK(Ref<Vec3f> kaajmma);
        virtual void kAmaJAK(Ref<Mat3f> kaaakka);
        virtual Ref<Mat3f> KAMAjAK(Ref<Mat3f> kaaakka);
        virtual void KAmAJAK();
        virtual Ref<Mat3f> kamaJAK();
        virtual void KAMAJAK(float n);
        virtual void KaMaJak(float n);
        virtual void kAmAJAK(float n);
        virtual Ref<Mat3f> kaMAJAK(float n);
        virtual Ref<Mat3f> KaMAJAK(float n);
        virtual Ref<Mat3f> KAmaJAK(float n);
        virtual void kAMaJAK();
        virtual Ref<Mat3f> KaMaJAK();
        virtual void kamAJAK(Ref<Vec3f> kaajmma);
        virtual void KamAJAK(Ref<Vec3f> kaajmma);
        virtual Ref<Mat3f> KamaJak(Ref<Vec3f> kaajmma);
        virtual Ref<Mat3f> kAMajAK(Ref<Vec3f> kaajmma);
        virtual String toString();
        virtual void releaseReferences();
    };
    class Quaternionf : public Object {
      public:
        float x{};
        float y{};
        float z{};
        float w{};
        static double AJAKKAm;
        Quaternionf(float aJakKAm, float aJakKAm2, float ajAKKAm, float ajAKKAm2);
        Quaternionf(double n, double n2, double n3, double n4);
        Quaternionf(Ref<Vec3f> kaajmma, float ajAKKAm);
        Quaternionf(Ref<Vec3f> kaajmma);
        Quaternionf(Ref<Quaternionf> kajjkkk);
        Quaternionf();
        virtual void aKkAMAj(Ref<Quaternionf> kajjkkk);
        virtual void akkaMAj(float aJakKAm, float aJakKAm2, float ajAKKAm, float ajAKKAm2);
        virtual void AKKamAj(double n, double n2, double n3, double n4);
        virtual float AkKamAj();
        virtual void AkKAmAj(float n);
        virtual void AkKAMAj();
        virtual float AkkAMAj(Ref<Quaternionf> kajjkkk);
        virtual float AkkamAj(Ref<Quaternionf> kajjkkk);
        virtual void AkkaMAj(Ref<Quaternionf> kajjkkk);
        virtual void akkamAj();
        virtual void AKKAmAj();
        virtual void akKAMAj();
        virtual void aKkaMAj();
        virtual void aKKAMAj(Ref<Quaternionf> kajjkkk);
        virtual void aKKamAj(Ref<Mat3f> kaaakka);
        virtual void aKkamAj(Ref<Mat3f> kaaakka);
        virtual void AKkAMAj(float n, float n2, float n3, float n4);
        virtual void AKkaMAj(Ref<Vec3f> kaajmma, float n);
        virtual void AKKAMAj();
        virtual float akKAmAj(Ref<Vec3f> kaajmma);
        virtual void AKkamAj(Ref<Mat3f> kaaakka);
        virtual void akKamAj(Ref<Quaternionf> kajjkkk, Ref<Quaternionf> kajjkkk2, float n, float n2);
        virtual void akkAMAj(Ref<Quaternionf> kajjkkk, Ref<Quaternionf> kajjkkk2, float n, float n2);
        virtual String toString();
        virtual void releaseReferences();
    };
    class UvCoord : public Object {
      public:
        float u{};
        float v{};
        UvCoord();
        UvCoord(Ref<UvCoord> kajjmmk);
        UvCoord(float jaKkaMA, float jakkaMA);
        UvCoord(double n, double n2);
        virtual void set(Ref<UvCoord> kajjmmk);
        virtual void set(float jaKkaMA, float jakkaMA);
        virtual void set(double n, double n2);
        virtual void releaseReferences();
    };
    class Vertex : public Vec3f {
      public:
        static std::int32_t kAmaJAK;
        static std::int32_t KaMAJAK;
        static std::int32_t kaMAJAK;
        static std::int32_t KAMAJAK;
        static std::int32_t kAMAJAK;
        static std::int32_t KamAJAK;
        static std::int32_t kamAJAK;
        static std::int32_t KAmAJAK;
        static std::int32_t kAmAJAK;
        static std::int32_t KaMajAK;
        static std::int32_t kaMajAK;
        static std::int32_t KAMajAK;
        float kAMajAK{};
        float KamajAK{};
        float kamajAK{};
        float KAmajAK{};
        float kAmajAK{};
        float KaMAjAK{};
        float kaMAjAK{};
        float KAMAjAK{};
        std::int32_t kAMAjAK{};
        float KamAjAK{};
        Vertex();
        Vertex(float majaKka, float majaKka2, float mAjaKka);
        Vertex(double n, double n2, double n3);
        Vertex(Ref<Vertex> majjmka);
        virtual void KAMajak(float kaMAjAK, float kamAjAK);
        virtual void kAMajak(float kAmajAK, float kAmajAK2, float kaMAjAK);
        virtual void kaMajak(Ref<Vertex> majjmka);
        virtual void releaseReferences();
    };
    class Camera : public Object {
      public:
        std::int32_t viewportWidth{};
        std::int32_t viewportHeight{};
        float AmaJAkK{};
        float amaJAkK{};
        Ref<Vec3f> position{};
        Ref<Mat3f> orientation{};
        Ref<Vec3f> upVector{};
        float rollRadians{};
        float nearClip{};
        float farClip{};
        float fogStart{};
        virtual void lookAt(Ref<Vec3f> kaajmma);
        virtual void lookAlong(Ref<Vec3f> kaajmma);
        Camera();
        virtual void releaseReferences();
    };
    class ScalarFieldVertex : public Vec3f {
      public:
        float amAJAkK{};
        ScalarFieldVertex();
        ScalarFieldVertex(float majaKka, float majaKka2, float mAjaKka, float amAJAkK);
        virtual void jAKKAMa(float majaKka, float majaKka2, float mAjaKka, float amAJAkK);
        virtual void releaseReferences();
    };
    class IsoSurfaceIntersection : public Vec3f {
      public:
        static float kaMaJAK;
        IsoSurfaceIntersection();
        virtual void kamaJak(Ref<ScalarFieldVertex> kaaakkk, Ref<ScalarFieldVertex> kaaakkk2);
        virtual void releaseReferences();
    };
    class SortableItem : public Object {
      public:
        float sortKey{};
        SortableItem();
        virtual void releaseReferences();
    };
    class RenderPrimitive : public SortableItem {
      public:
        std::int32_t amAJAKK{};
        Ref<IndexedSurface> AMAJAKK{};
        Ref<RgbSurface> aMAJAKK{};
        float AmaJAKK{};
        float amaJAKK{};
        float AMaJAKK{};
        static Array<Ref<Object>> aMaJAKK;
        static std::int32_t AmAjaKK;
        virtual void amajaKK() = 0;
        virtual void aMAjaKK() = 0;
        virtual void AmajaKK() = 0;
        RenderPrimitive();
        virtual void releaseReferences();
    };
    class Triangle : public RenderPrimitive {
      public:
        Ref<Vertex> amAJAkk{};
        Ref<Vertex> AMAJAkk{};
        Ref<Vertex> aMAJAkk{};
        Ref<UvCoord> AmaJAkk{};
        Ref<UvCoord> amaJAkk{};
        Ref<UvCoord> AMaJAkk{};
        std::int32_t aMaJAkk{};
        Triangle(Ref<MeshObject> mmaakkk, std::int32_t n, std::int32_t n2, std::int32_t n3);
        Triangle(Ref<MeshObject> mmaakkk, std::int32_t n, std::int32_t n2, std::int32_t n3, std::int32_t n4,
                 std::int32_t n5, std::int32_t n6);
        Triangle(Ref<Vertex> amAJAkk, Ref<Vertex> amajAkk, Ref<Vertex> amajAkk2);
        Triangle(Ref<Vertex> amAJAkk, Ref<Vertex> amajAkk, Ref<Vertex> amajAkk2, Ref<UvCoord> amaJAkk,
                 Ref<UvCoord> amaJAkk2, Ref<UvCoord> aMaJAkk);
        Triangle(Ref<Triangle> kajjkka);
        Triangle(Ref<Triangle> kajjkka, Ref<Vertex> amAJAkk, Ref<Vertex> amajAkk, Ref<Vertex> amajAkk2);
        Triangle(Ref<Triangle> kajjkka, Ref<Vertex> amAJAkk, Ref<Vertex> amajAkk, Ref<Vertex> amajAkk2,
                 Ref<UvCoord> amaJAkk, Ref<UvCoord> amaJAkk2, Ref<UvCoord> aMaJAkk);
        virtual void AmajAkk(Ref<Triangle> kajjkka);
        virtual void aMAjaKK();
        virtual void amajaKK();
        virtual void AmajaKK();
        virtual void releaseReferences();
    };
    class MeshObject : public Object {
      public:
        String mAjAKka{};
        bool MaJakka{};
        Array<Ref<Object>> maJakka{};
        Array<Ref<Object>> MAJakka{};
        Array<Ref<Object>> mAJakka{};
        Ref<Vec3f> Majakka{};
        Ref<Vec3f> majakka{};
        Ref<Vec3f> MAjakka{};
        Ref<Mat3f> mAjakka{};
        float MaJAkka{};
        bool maJAkka{};
        bool MAJAkka{};
        bool mAJAkka{};
        Ref<Camera> MajAkka{};
        Ref<MeshObject> majAkka{};
        std::int32_t MAjAkka{};
        Ref<Mat3f> mAjAkka{};
        float MaJaKKa{};
        std::int32_t maJaKKa{};
        std::int32_t MAJaKKa{};
        std::int32_t mAJaKKa{};
        std::int32_t MajaKKa{};
        float majaKKa{};
        float MAjaKKa{};
        float mAjaKKa{};
        float MaJAKKa{};
        float maJAKKa{};
        std::int32_t MAJAKKa{};
        float mAJAKKa{};
        bool MajAKKa{};
        Ref<Mat3f> majAKKa{};
        static std::int32_t MAjAKKa;
        static Array<Ref<Object>> mAjAKKa;
        static std::int32_t MaJakKa;
        static Array<Ref<Object>> maJakKa;
        MeshObject();
        MeshObject(Ref<MeshObject> mmaakkk);
        virtual void JaKKaMA(bool majAkka);
        virtual void jAkKaMA(String s);
        virtual String jAKKaMA();
        virtual void jakkama(Ref<RgbSurface> amajakk, Ref<RgbSurface> amajakk2);
        virtual void JAKKaMA();
        virtual void jaKkama(Ref<Vec3f> kaajmma);
        virtual void Jakkama(Ref<Vec3f> kaajmma);
        virtual void jAkkaMA(float n, float n2, float n3);
        virtual void JakKAma();
        virtual void jAKkAma(Ref<RgbSurface> amajakk, float n);
        virtual void JAkKaMA(Ref<RgbSurface> amajakk);
        virtual void jAKKAma(Ref<RgbSurface> amajakk, Ref<IndexedSurface> amajakk2);
        virtual void JAKkAma(std::int32_t amAJAKK);
        virtual void jakkaMA();
        virtual void JaKkama(Ref<Camera> majAkka, std::int32_t n);
        virtual Ref<Vec3f> jakKaMA();
        virtual void JaKkAma();
        virtual void jaKkAma();
        virtual void jakkAma();
        virtual void JAKkaMA();
        virtual void jakKAma(Array<Ref<Object>> array, std::int32_t n);
        virtual void JAkkama();
        virtual void jaKKAma(Array<Ref<Object>> array, std::int32_t n);
        virtual void JakkaMA();
        virtual void JAkKAma(Array<Ref<Object>> array, std::int32_t n);
        virtual void jAKkaMA();
        virtual void JAkkaMA(Array<Ref<Object>> array, std::int32_t n);
        virtual void jAkKAma();
        virtual void jAKkama(Array<Ref<Object>> array, std::int32_t n);
        virtual void JakkAma();
        virtual void JAKKAma(Array<Ref<Object>> array, std::int32_t n);
        virtual void jaKKaMA();
        virtual void JakKaMA();
        virtual void JaKKAma(Ref<Triangle> kajjkka);
        virtual void jAkkAma();
        virtual void JAkkAma(Ref<Triangle> kajjkka, Ref<Vertex> majjmka, Ref<Vertex> majjmka2, Ref<Vertex> majjmka3,
                             Ref<UvCoord> kajjmmk, Ref<UvCoord> kajjmmk2, Ref<UvCoord> kajjmmk3);
        virtual void jAkkama(Ref<Triangle> kajjkka, Ref<Vertex> majjmka, Ref<Vertex> majjmka2, Ref<Vertex> majjmka3,
                             Ref<UvCoord> kajjmmk, Ref<UvCoord> kajjmmk2, Ref<UvCoord> kajjmmk3);
        virtual void JAKkama(Array<Ref<Object>> array, std::int32_t n);
        static void initialize_static();
        virtual void releaseReferences();
    };
    class TexturedTriangleRasterizer : public Object {
      public:
        Ref<IndexedSurface> mAJAkKa{};
        Ref<RgbSurface> MajAkKa{};
        Ref<RgbSurface> majAkKa{};
        std::int32_t MAjAkKa{};
        std::int32_t mAjAkKa{};
        std::int32_t AmAjAkK{};
        std::int32_t amAjAkK{};
        std::int32_t AMAjAkK{};
        std::int32_t aMAjAkK{};
        std::int32_t AmajAkK{};
        float amajAkK{};
        float AMajAkK{};
        float aMajAkK{};
        float AmAJAkK{};
        float amAJAkK{};
        float AMAJAkK{};
        float aMAJAkK{};
        float AmaJAkK{};
        float amaJAkK{};
        float AMaJAkK{};
        float aMaJAkK{};
        std::int32_t AmAjakK{};
        std::int32_t amAjakK{};
        std::int32_t AMAjakK{};
        static float aMAjakK;
        static float AmajakK;
        std::int32_t amajakK_field{};
        std::int32_t AMajakK_field{};
        std::int32_t aMajakK_field{};
        std::int32_t AmAJakK_field{};
        std::int32_t amAJakK_field{};
        static std::int32_t AMAJakK_field;
        static std::int32_t aMAJakK_field;
        static std::int32_t AmaJakK_field;
        static std::int32_t AmAJakK(float n);
        static std::int32_t aMAjAKK(float n);
        static std::int32_t aMaJakK(double n);
        static std::int32_t AMaJakK(float n);
        TexturedTriangleRasterizer(Ref<RgbSurface> majAkKa);
        virtual void amAjAKK(Ref<Triangle> kajjkka);
        virtual void aMajakK(Ref<Triangle> kajjkka, std::int32_t n, std::int32_t n2);
        virtual void amAJakK(std::int32_t i, std::int32_t n);
        virtual void aMAJakK(std::int32_t i, std::int32_t n);
        virtual void AmajAKK(std::int32_t i, std::int32_t n);
        virtual void AmaJakK(std::int32_t i, std::int32_t n);
        virtual void amaJakK(std::int32_t i, std::int32_t n);
        virtual void AmAjAKK(std::int32_t i, std::int32_t n);
        virtual void AMAJakK(std::int32_t i, std::int32_t n);
        virtual void AMAjAKK(std::int32_t i, std::int32_t n);
        virtual void amajakK(std::int32_t i, std::int32_t n);
        virtual void AMajakK(std::int32_t i, std::int32_t n);
        virtual void releaseReferences();
    };
    class LineRasterizer : public Object {
      public:
        bool KaMaJAk_field{};
        bool kaMaJAk_field{};
        std::int32_t KAMaJAk_field{};
        float kAMaJAk_field{};
        std::int32_t KamaJAk_field{};
        std::int32_t kamaJAk_field{};
        Ref<RgbSurface> KAmaJAk_field{};
        std::int32_t kAmaJAk{};
        std::int32_t KaMAJAk{};
        std::int32_t kaMAJAk{};
        std::int32_t KAMAJAk{};
        static float kAMAJAk;
        static std::int32_t KamAJAk;
        LineRasterizer(Ref<RgbSurface> kAmaJAk, std::int32_t kamaJAk, std::int32_t kamaJAk2);
        virtual void KAmaJAk(std::int32_t kaMaJAk);
        virtual void KAmAjak(float kaMaJAk);
        virtual void kamaJAk(bool kaMaJAk);
        virtual void KaMaJAk(Ref<Triangle> kajjkka);
        virtual std::int32_t kAMaJAk(float n, float n2);
        virtual void kaMaJAk(std::int32_t n, std::int32_t n2, float n3, float n4, float n5, float n6, float n7);
        virtual void kAmAjak(std::int32_t n, std::int32_t n2, float n3, float n4, float n5, float n6, float n7);
        virtual void KAMaJAk(std::int32_t n, std::int32_t n2, std::int32_t n3);
        virtual void KamAjak(float n, float n2, float n3, float n4, std::int32_t n5, std::int32_t n6, std::int32_t n7);
        virtual void kamAjak(float n, float n2, float n3, float n4, std::int32_t n5, std::int32_t n6, std::int32_t n7);
        virtual void KamaJAk(float n, float n2, float n3, float n4, std::int32_t n5, std::int32_t n6, std::int32_t n7);
        virtual void releaseReferences();
    };
    class RgbSurface : public SoftwareImageSurface {
      public:
        Array<std::int32_t> AmAjakk_field{};
        Array<std::int32_t> amAjakk_field{};
        Array<std::int32_t> AMAjakk_field{};
        Array<std::int32_t> aMAjakk_field{};
        static std::int32_t Amajakk_field;
        static std::int32_t amajakk_field;
        static std::int32_t AMajakk_field;
        RgbSurface(std::int32_t n, std::int32_t n2, Array<std::int32_t> array);
        RgbSurface(std::int32_t n, std::int32_t n2, std::int32_t n3, bool b);
        virtual void publishRegion(std::int32_t n, std::int32_t n2, std::int32_t n3, std::int32_t n4);
        virtual void Amajakk();
        virtual void AMaJAkk(Array<std::int32_t> array);
        static std::int32_t AmAJakk(std::int32_t n);
        static std::int32_t AMaJakk(std::int32_t n, std::int32_t n2, std::int32_t n3);
        virtual void aMaJAkk();
        virtual void aMAjakk(std::int32_t n);
        virtual void amajakk(std::int32_t n);
        virtual void AMajakk(std::int32_t n);
        virtual void aMAJAkk(std::int32_t n);
        virtual void amaJakk(Ref<RgbSurface> mmajkka, std::int32_t n, std::int32_t n2, Ref<RgbSurface> mmajkka2,
                             std::int32_t n3, std::int32_t n4, std::int32_t n5, std::int32_t n6, std::int32_t n7,
                             std::int32_t n8, double n9);
        virtual void amAjakk(Ref<RgbSurface> mmajkka, std::int32_t n, std::int32_t n2, Ref<RgbSurface> mmajkka2,
                             std::int32_t n3, std::int32_t n4, std::int32_t n5, std::int32_t n6, std::int32_t n7,
                             std::int32_t n8, double n9, double n10);
        virtual void amaJAkk(Ref<RgbSurface> mmajkka, std::int32_t n, std::int32_t n2);
        virtual void amajAkk(Ref<RgbSurface> mmajkka, std::int32_t n, std::int32_t n2, std::int32_t n3, std::int32_t n4,
                             std::int32_t n5, std::int32_t n6);
        virtual void AmAJAkk(Ref<IndexedSurface> maaakka);
        virtual void AMAjakk(Ref<IndexedSurface> maaakka);
        virtual void AMAJakk(Ref<RgbSurface> mmajkka, std::int32_t n, std::int32_t n2);
        virtual void amAJAkk(Ref<RgbSurface> mmajkka, std::int32_t x, std::int32_t y);
        virtual void amAJakk(float n);
        virtual void AmaJakk(float n);
        virtual void aMajAkk();
        virtual void aMAJakk();
        virtual void AMajAkk();
        virtual void AmAjakk(std::int32_t n);
        virtual void aMajakk(Array<std::int32_t> array, Array<std::int32_t> array2, Array<std::int32_t> array3);
        virtual void AMAJAkk(Ref<RgbSurface> mmajkka, float n, float n2, float n3, float n4);
        virtual void AmaJAkk(std::int32_t n, std::int32_t n2);
        virtual void releaseReferences();
    };
    class IndexedSurface : public SoftwareImageSurface {
      public:
        Array<std::int8_t> kamAJaK_field{};
        Array<std::int8_t> KAmAJaK_field{};
        Array<std::int8_t> kAmAJaK_field{};
        Array<std::int8_t> KaMajaK_field{};
        Array<std::int8_t> kaMajaK_field{};
        Array<std::int8_t> KAMajaK_field{};
        Array<std::int8_t> kAMajaK_field{};
        Array<std::int32_t> KamajaK_field{};
        std::int32_t kamajaK_field{};
        Array<std::int8_t> KAmajaK_field{};
        static Array<std::int8_t> kAmajaK_field;
        IndexedSurface(std::int32_t n, std::int32_t n2, Array<std::int8_t> array, Array<std::int8_t> array2,
                       Array<std::int8_t> array3, Array<std::int8_t> array4);
        IndexedSurface(std::int32_t n, std::int32_t n2, std::int32_t kamajaK, bool b);
        virtual void kAmAjaK(Ref<IndexedSurface> maaakka);
        virtual void KAMAjaK(Ref<IndexColorModel> indexColorModel);
        virtual void kaMAjaK(Array<std::int8_t> array, Array<std::int8_t> array2, Array<std::int8_t> array3);
        virtual void KaMajaK();
        virtual void KAmAJaK(Array<std::int8_t> array, Array<std::int8_t> array2, Array<std::int8_t> array3,
                             Array<std::int8_t> array4);
        virtual void kamajaK();
        virtual void publishRegion(std::int32_t n, std::int32_t n2, std::int32_t n3, std::int32_t n4);
        virtual void KAMajaK(std::int32_t n);
        virtual void kamAJaK();
        virtual void kAMajaK();
        virtual void kAMAjaK(std::int32_t n, std::int32_t n2, std::int32_t n3, std::int32_t n4, std::int32_t n5,
                             std::int32_t n6);
        virtual void KAMAJaK();
        virtual void KAmajaK(double n);
        virtual void KamajaK(double n, double n2, double n3);
        virtual void KamAJaK(double n, double n2);
        virtual void KAmAjaK(double n, double n2, double n3, double n4);
        virtual void kaMajaK(double n, double n2, double n3, double n4, double n5, double n6);
        virtual void kAMAJaK(Array<std::int8_t> array, double n, double n2, double n3, double n4, double n5, double n6);
        virtual void kAmajaK(std::int32_t n);
        virtual void KaMAjaK(std::int32_t n);
        virtual void kAmAJaK(Ref<IndexedSurface> maaakka, std::int32_t n, std::int32_t n2);
        virtual void KamAjaK(Ref<IndexedSurface> maaakka, std::int32_t n, std::int32_t n2, std::int32_t n3,
                             std::int32_t n4, std::int32_t n5, std::int32_t n6);
        virtual void kamAjaK(Ref<RgbSurface> mmajkka, std::int8_t b);
        static void initialize_static();
        virtual void releaseReferences();
    };
    class ObjectSortEntry : public SortableItem {
      public:
        Ref<Object> amAjaKK{};
        ObjectSortEntry();
        virtual String toString();
        virtual void releaseReferences();
    };
    class DepthSorter : public Object {
      public:
        Array<Ref<Object>> mAjakkA{};
        DepthSorter(std::int32_t n);
        DepthSorter(std::int32_t n, bool b);
        DepthSorter(Array<Ref<Object>> mAjakkA);
        virtual void mAJakkA(std::int32_t n);
        virtual void maJakkA(std::int32_t n, std::int32_t n2);
        virtual void MAJakkA(std::int32_t n, std::int32_t n2);
        virtual std::int32_t MaJakkA(std::int32_t n, std::int32_t n2);
        virtual void releaseReferences();
    };
    class ViewFrustum : public Object {
      public:
        Ref<Vec3f> KkaMaja{};
        Ref<Vec3f> kkaMaja{};
        Ref<Vec3f> KKaMaja{};
        Ref<Vec3f> kKaMaja{};
        Ref<Vec3f> KkAmAJa{};
        Ref<Vec3f> kkAmAJa{};
        Ref<Vec3f> KKAmAJa{};
        Ref<Vec3f> kKAmAJa{};
        Ref<Vec3f> KkamAJa{};
        Ref<Vec3f> kkamAJa{};
        float KKamAJa{};
        float kKamAJa{};
        virtual void kKAMajA(Ref<Camera> mmjjmkk, Ref<MeshObject> mmaakkk);
        virtual bool KKAMajA(Ref<Vec3f> kaajmma);
        virtual std::int32_t KkaMajA(Ref<MeshObject> mmaakkk);
        ViewFrustum();
        virtual void releaseReferences();
    };
    class MarchingCubesTables : public Object {
      public:
        static Array<std::int32_t> KkAmAja;
        static Array<Array<std::int32_t>> kkAmAja;
        virtual void releaseReferences();
    };
    class MetaballMesh : public MeshObject {
      public:
        static float AKkAmAj;
        static std::int32_t aKkAmAj;
        static std::int32_t JaKkAmA;
        static std::int32_t jaKkAmA;
        Array<Ref<Object>> JAKkAmA{};
        Array<Ref<Object>> jAKkAmA{};
        Array<float> JakkAmA{};
        Array<bool> jakkAmA{};
        std::int32_t JAkkAmA{};
        std::int32_t jAkkAmA{};
        std::int32_t JaKKAmA{};
        std::int32_t jaKKAmA{};
        static float JAKKAmA;
        static float jAKKAmA;
        Ref<ScalarFieldVertex> JakKAmA{};
        Ref<ScalarFieldVertex> jakKAmA{};
        Ref<ScalarFieldVertex> JAkKAmA{};
        Ref<ScalarFieldVertex> jAkKAmA{};
        Ref<ScalarFieldVertex> JaKkamA{};
        Ref<ScalarFieldVertex> jaKkamA{};
        Ref<ScalarFieldVertex> JAKkamA{};
        Ref<ScalarFieldVertex> jAKkamA{};
        std::int32_t JakkamA = 1;
        std::int32_t jakkamA = 24;
        std::int32_t JAkkamA = 576;
        MetaballMesh();
        virtual void JaKkama(Ref<Camera> majAkka, std::int32_t n);
        virtual void kkaMaJa(Array<Ref<Object>> array, std::int32_t n);
        virtual void JAKkaMA();
        virtual void kKAMaJa(float n);
        virtual void KkAMaJa(Ref<Vertex> majjmka, Ref<ScalarFieldVertex> kaaakkk, Ref<ScalarFieldVertex> kaaakkk2);
        virtual std::int32_t kkAMaJa();
        virtual void KkaMaJa();
        virtual void KKAMaJa(Ref<Graphics> graphics);
        virtual void releaseReferences();
    };
    class ParticleVertex : public Vertex {
      public:
        Ref<Vec3f> kAmAjak{};
        ParticleVertex();
        ParticleVertex(float majaKka, float majaKka2, float mAjaKka);
        virtual void releaseReferences();
    };
    class ParticleCloudMesh : public MeshObject {
      public:
        float AKKamaJ{};
        Array<Ref<Object>> aKKamaJ{};
        static std::int32_t AkkamaJ;
        static std::int32_t akkamaJ;
        std::int32_t AKkamaJ{};
        float aKkamaJ{};
        float AkKAmaJ{};
        std::int32_t akKAmaJ{};
        float AKKAmaJ{};
        ParticleCloudMesh(std::int32_t n, float akKamaJ);
        virtual void kkAmaJA(std::int32_t n);
        virtual std::int32_t KkAmaJA();
        virtual void KkaMAJA(std::int32_t aKkamaJ);
        virtual void JaKkama(Ref<Camera> majAkka, std::int32_t n);
        virtual void kkaMAJA();
        virtual void kKaMAJA(Ref<Vec3f> kaajmma, Ref<Vec3f> kaajmma2, float n, float n2);
        virtual void KKaMAJA(Ref<Vec3f> kaajmma, float n, float n2, float n3);
        virtual void releaseReferences();
    };
    class RadialFlareMesh : public MeshObject {
      public:
        Ref<RgbSurface> MAjAKKA{};
        Ref<IndexedSurface> mAjAKKA{};
        float MaJakKA{};
        float maJakKA{};
        float MAJakKA{};
        float mAJakKA{};
        float MajakKA{};
        RadialFlareMesh(Ref<RgbSurface> mAjAKKA, Ref<IndexedSurface> mAjAKKA2);
        virtual void JaKkama(Ref<Camera> majAkka, std::int32_t n);
        virtual void JAKKAma(Array<Ref<Object>> array, std::int32_t n);
        virtual void JAKkaMA();
        virtual void releaseReferences();
    };
    class WireframeMesh : public MeshObject {
      public:
        bool aJAkkAM{};
        std::int32_t AjakkAM{};
        WireframeMesh();
        WireframeMesh(Ref<MeshObject> mmaakkk);
        virtual void AkKAmAJ();
        virtual void JaKkama(Ref<Camera> majAkka, std::int32_t n);
        virtual void aKkamAJ();
        virtual void akKAmAJ(Array<Ref<Object>> array, std::int32_t n);
        virtual void jAKkama(Array<Ref<Object>> array, std::int32_t n);
        virtual void releaseReferences();
    };
    class BackdropMesh : public MeshObject {
      public:
        float MAjakkA{};
        BackdropMesh(Ref<DesktopDemoBase> kmaamma, Ref<URL> url, bool b);
        virtual void JaKkama(Ref<Camera> mmjjmkk, std::int32_t n);
        virtual void releaseReferences();
    };
    class HeightFieldMesh : public MeshObject {
      public:
        std::int32_t JAkKAMa{};
        std::int32_t jAkKAMa{};
        Array<Array<std::int16_t>> JaKkaMa{};
        std::int32_t jaKkaMa{};
        std::int32_t JAKkaMa{};
        std::int32_t jAKkaMa{};
        std::int32_t JakkaMa{};
        std::int32_t jakkaMa{};
        std::int32_t JAkkaMa{};
        float jAkkaMa{};
        float JaKKaMa{};
        Ref<RgbSurface> jaKKaMa{};
        Ref<IndexedSurface> JAKKaMa{};
        Ref<IndexedSurface> jAKKaMa{};
        Ref<RgbSurface> JakKaMa{};
        bool jakKaMa{};
        Array<Ref<Object>> JAkKaMa{};
        Array<Ref<Object>> jAkKaMa{};
        std::int32_t AjAkKaM{};
        std::int32_t ajAkKaM{};
        std::int32_t AJAkKaM{};
        std::int32_t aJAkKaM{};
        float AjakKaM{};
        float ajakKaM{};
        static std::int32_t AJakKaM;
        static std::int32_t aJakKaM;
        bool AjAKKaM{};
        bool ajAKKaM{};
        static float AJAKKaM;
        HeightFieldMesh(Array<Array<std::int16_t>> jaKkaMa, float jAkkaMa, float jaKKaMa, Ref<Camera> mmjjmkk,
                        bool jakKaMa);
        virtual void AKkaMAJ(std::int32_t n, std::int32_t n2, float n3, std::int32_t n4);
        virtual void AkKAMAJ();
        virtual float akKAMAJ(float a, float a2, float a3, float a4, float b);
        virtual float AKKAMAJ(float a, float a2, float a3, float a4, float b);
        virtual void aKkaMAJ();
        virtual void JAKkaMA();
        virtual void aKKAMAJ();
        virtual void JaKkama(Ref<Camera> majAkka, std::int32_t n);
        virtual void releaseReferences();
    };
    class TrackKeyframe : public Object {
      public:
        float MaJAkkA{};
        float maJAkkA{};
        float MAJAkkA{};
        float mAJAkkA{};
        float MajAkkA{};
        float majAkkA{};
        Array<float> MAjAkkA{};
        Array<std::int32_t> mAjAkkA{};
        Array<Ref<Object>> MaJaKKA{};
        Array<Ref<Object>> maJaKKA{};
        Array<Ref<Object>> MAJaKKA{};
        TrackKeyframe(float maJAkkA, float maJAkkA2, float majAkkA, float majAkkA2, Array<float> mAjAkkA);
        TrackKeyframe(float maJAkkA, Ref<TrackKeyframe> majjmma);
        TrackKeyframe(Ref<TrackKeyframe> majjmma);
        TrackKeyframe(float maJAkkA, float maJAkkA2, float majAkkA, float majAkkA2, float n);
        TrackKeyframe(float maJAkkA, float maJAkkA2, float majAkkA, float majAkkA2, float n, float n2);
        TrackKeyframe(float maJAkkA, float maJAkkA2, float majAkkA, float majAkkA2, float n, float n2, float n3);
        TrackKeyframe(float maJAkkA, float maJAkkA2, float majAkkA, float majAkkA2, float n, float n2, float n3,
                      float n4);
        TrackKeyframe(float maJAkkA, float maJAkkA2, float majAkkA, float majAkkA2, Ref<Quaternionf> kajjkkk);
        TrackKeyframe(float maJAkkA, float maJAkkA2, float majAkkA, float majAkkA2, Array<Ref<Object>> maJaKKA);
        virtual void releaseReferences();
    };
    class SplineTrack : public Object {
      public:
        std::int32_t AJAKkaM{};
        static std::int32_t aJAKkaM;
        static std::int32_t AjaKkaM;
        static std::int32_t ajaKkaM;
        std::int32_t AJaKkaM{};
        static std::int32_t aJaKkaM;
        static std::int32_t AjAkKAM;
        static std::int32_t ajAkKAM;
        std::int32_t AJAkKAM{};
        std::int32_t aJAkKAM{};
        Array<Ref<Object>> AjakKAM{};
        Ref<TrackKeyframe> ajakKAM{};
        Ref<TrackKeyframe> AJakKAM{};
        float aJakKAM{};
        Array<float> AjAKKAM{};
        Array<float> ajAKKAM{};
        Array<std::int32_t> AJAKKAM{};
        Array<std::int32_t> aJAKKAM{};
        float AjaKKAM{};
        float ajaKKAM{};
        float AJaKKAM{};
        float aJaKKAM{};
        Array<float> AjAkkAM{};
        Array<std::int32_t> ajAkkAM{};
        Array<Ref<Object>> AJAkkAM{};
        SplineTrack(Array<Ref<Object>> ajakKAM, std::int32_t ajaKkaM, std::int32_t aJaKkaM);
        virtual Ref<TrackKeyframe> akkamAJ(std::int32_t n);
        virtual void AkkamAJ(std::int32_t ajAkKAM);
        virtual void AKKamAJ();
        virtual void AKkamAJ(Ref<TrackKeyframe> majjmma, Ref<TrackKeyframe> majjmma2, Ref<TrackKeyframe> majjmma3,
                             std::int32_t n);
        virtual void aKKamAJ(float aJakKAM);
        virtual void releaseReferences();
    };
    class SurfacePresenter : public Object {
      public:
        std::int32_t jAkkamA{};
        std::int32_t JaKKamA{};
        std::int32_t jaKKamA{};
        std::int32_t JAKKamA{};
        std::int32_t jAKKamA{};
        std::int32_t JakKamA{};
        bool jakKamA{};
        static bool JAkKamA;
        static std::int32_t jAkKamA;
        static std::int32_t JaKkAMA;
        static std::int32_t jaKkAMA;
        static std::int32_t JAKkAMA;
        static std::int32_t jAKkAMA;
        static std::int32_t JakkAMA;
        static std::int32_t jakkAMA;
        static std::int32_t JAkkAMA;
        static std::int32_t jAkkAMA;
        static std::int32_t JaKKAMA;
        static std::int32_t jaKKAMA;
        static std::int32_t JAKKAMA;
        static std::int32_t jAKKAMA;
        SurfacePresenter();
        virtual void akkaMaJ(Ref<DesktopDemoBase> kmaamma, std::int32_t n, std::int32_t n2);
        virtual void kKaMaJa(Ref<DesktopDemoBase> kmaamma, std::int32_t n, std::int32_t n2, std::int32_t n3);
        virtual void KKaMaJa(Ref<DesktopDemoBase> kmaamma, std::int32_t jaKKamA, std::int32_t jakKamA,
                             std::int32_t jakKamA2, std::int32_t jakKamA3);
        virtual void aKKaMaJ(Ref<Graphics> graphics, std::int32_t n, std::int32_t n2);
        virtual void AkkaMaJ(Array<Ref<Object>> array, std::int32_t n);
        virtual void AkKaMaJ(Ref<DesktopDemoBase> p0) = 0;
        virtual void AKKaMaJ(Ref<Graphics> p0, std::int32_t p1, std::int32_t p2) = 0;
        virtual void aKkaMaJ(Ref<Graphics> p0, std::int32_t p1, std::int32_t p2) = 0;
        virtual void AKkaMaJ(Ref<Triangle> p0) = 0;
        virtual void akKaMaJ() = 0;
        static void initialize_static();
        virtual void releaseReferences();
    };
    class RgbSurfacePresenter : public SurfacePresenter {
      public:
        Ref<RgbSurface> kamAJAk{};
        Ref<TexturedTriangleRasterizer> KAmAJAk{};
        Ref<LineRasterizer> kAmAJAk{};
        Ref<Image> KaMajAk{};
        Ref<Graphics> kaMajAk{};
        std::int32_t KAMajAk{};
        RgbSurfacePresenter();
        virtual void AkKaMaJ(Ref<DesktopDemoBase> kmaamma);
        virtual void AKkaMaJ(Ref<Triangle> kajjkka);
        virtual void AKKaMaJ(Ref<Graphics> graphics, std::int32_t n, std::int32_t n2);
        virtual void aKkaMaJ(Ref<Graphics> graphics, std::int32_t n, std::int32_t n2);
        virtual void KaMAJAk(std::int32_t kaMajAk);
        virtual void akKaMaJ();
        virtual void kAmaJAk(std::int32_t amAJakk);
        virtual void releaseReferences();
    };
    class SceneRenderer : public Object {
      public:
        Ref<Vector> mAjAKkA_field{};
        Array<Ref<Object>> MaJakkA{};
        Ref<DepthSorter> maJakkA{};
        static bool MAJakkA;
        static bool mAJakkA;
        static bool MajakkA;
        static bool majakkA;
        virtual void MAjAKkA();
        virtual void mAjAKkA(Ref<Camera> mmjjmkk, Ref<SurfacePresenter> kmjjmmk);
        virtual void MajAKkA(Ref<SurfacePresenter> kmjjmmk);
        virtual void mAJAKkA(Ref<MeshObject> obj);
        virtual void majAKkA(float n);
        virtual void MAJAKkA(float majakKa, Ref<Camera> mmjjmkk);
        SceneRenderer();
        static void initialize_static();
        virtual void releaseReferences();
    };
    class AseSceneLoader : public SceneRenderer {
      public:
        Ref<SplineTrack> aJakkam{};
        Ref<SplineTrack> AjAKkam{};
        Array<Ref<Object>> ajAKkam{};
        Ref<Hashtable> AJAKkam{};
        Ref<Hashtable> aJAKkam{};
        Ref<Camera> AjaKkam = make_ref<Camera>();
        Ref<Vec3f> ajaKkam = make_ref<Vec3f>();
        Array<String> AJaKkam{};
        static void AKKamaj(Ref<Hashtable> hashtable, Ref<DataInputStream> dataInputStream);
        virtual void majAKkA(float f);
        virtual void MAJAKkA(float f, Ref<Camera> mmjjmkk2);
        AseSceneLoader();
        virtual Ref<StringTokenizer> akkAMaj(Ref<Vector> vector, std::int32_t n);
        virtual Ref<Vector> AKkAmaj(Ref<Hashtable> hashtable);
        virtual Ref<Vector> aKkAMaj(Ref<Hashtable> hashtable);
        virtual void aKKAMaj(Ref<Hashtable> hashtable, Ref<Object> object);
        virtual Ref<Camera> aKKamaj(Ref<Hashtable> hashtable);
        virtual void akkAmaj(Ref<Hashtable> hashtable, Ref<MeshObject> mmaakkk2);
        virtual void AkKamaj(Ref<Hashtable> hashtable, Ref<MeshObject> mmaakkk2);
        virtual void akKAmaj(Ref<Hashtable> hashtable, Ref<MeshObject> mmaakkk2);
        virtual void AkKAmaj(Ref<Hashtable> hashtable, Ref<MeshObject> mmaakkk2);
        virtual Ref<MeshObject> akkamaj(Ref<Hashtable> hashtable);
        virtual Ref<MeshObject> AKkamaj(Ref<Hashtable> hashtable);
        virtual void Akkamaj(Ref<Hashtable> hashtable, Array<String> stringArray);
        static float AkkAmaj(String string);
        static double akKAMaj(String string);
        static std::int32_t AKkAMaj(String string);
        static Ref<Hashtable> aKKAmaj(Ref<Object> object);
        static Ref<AseSceneLoader> akKamaj(Ref<URL> uRL);
        static Ref<AseSceneLoader> AKKAMaj(Ref<InputStream> inputStream);
        static Ref<AseSceneLoader> AkkAMaj(Ref<URL> uRL, Array<String> stringArray);
        static Ref<AseSceneLoader> aKkamaj(Ref<InputStream> inputStream, Array<String> stringArray);
        virtual void AKKAmaj(Ref<URL> uRL, Array<String> stringArray);
        virtual void releaseReferences();
    };
    class IguMeshLoader : public Object {
      public:
        IguMeshLoader();
        static Ref<MeshObject> kKAMAJA(Ref<URL> url);
        static double KKAMAJA(String substring);
        static std::int32_t kkAMAJA(String substring);
        virtual void releaseReferences();
    };
    class Scene : public Object {
      public:
        Scene();
        virtual String getSceneId() = 0;
        virtual void load(Ref<DesktopDemoBase> kmaamma);
        virtual void enter();
        virtual void dispose();
        virtual void render(Ref<RgbSurface> mmajkka, float n, float n2);
        virtual void handleMessage(String s, float n);
        virtual void releaseReferences();
    };
    class VehjeScene : public Scene {
      public:
        Ref<Camera> mAJaKKA{};
        Ref<SceneRenderer> MajaKKA{};
        Ref<RgbSurface> majaKKA{};
        Ref<MetaballMesh> MAjaKKA{};
        Ref<DesktopDemoBase> mAjaKKA{};
        VehjeScene();
        virtual String getSceneId();
        virtual void dispose();
        virtual void load(Ref<DesktopDemoBase> mAjaKKA);
        virtual void render(Ref<RgbSurface> mmajkka, float n, float n2);
        virtual void handleMessage(String s, float n);
        virtual void releaseReferences();
    };
    class PaaScene : public Scene {
      public:
        Ref<Camera> majAkKA{};
        Ref<AseSceneLoader> MAjAkKA{};
        Ref<RadialFlareMesh> mAjAkKA{};
        Ref<RgbSurface> MaJaKka{};
        Ref<RgbSurface> maJaKka{};
        Ref<MetaballMesh> MAJaKka{};
        Ref<DesktopDemoBase> mAJaKka{};
        PaaScene();
        virtual String getSceneId();
        virtual void load(Ref<DesktopDemoBase> maJaKka);
        virtual void enter();
        virtual void dispose();
        virtual void render(Ref<RgbSurface> mmajkka, float n, float n2);
        virtual void handleMessage(String s, float n);
        static Ref<RgbSurface> jAkKAMA(Ref<IndexedSurface> maaakka, float n, float n2, float n3);
        virtual void releaseReferences();
    };
    class TravScene : public Scene {
      public:
        Ref<Camera> MaJaKkA_field{};
        Ref<AseSceneLoader> maJaKkA{};
        Ref<RadialFlareMesh> MAJaKkA{};
        Ref<RgbSurface> mAJaKkA{};
        Ref<RgbSurface> MajaKkA{};
        Ref<RgbSurface> majaKkA{};
        Ref<DesktopDemoBase> MAjaKkA{};
        TravScene();
        virtual String getSceneId();
        virtual void dispose();
        virtual void load(Ref<DesktopDemoBase> mAjaKkA);
        virtual void render(Ref<RgbSurface> mmajkka, float majakKa, float n);
        virtual void handleMessage(String s, float n);
        static Ref<RgbSurface> MaJaKkA(Ref<IndexedSurface> maaakka, float n, float n2, float n3);
        virtual void releaseReferences();
    };
    class EvilScene : public Scene {
      public:
        Ref<Camera> AmAJakk{};
        Ref<AseSceneLoader> amAJakk{};
        Ref<DesktopDemoBase> AMAJakk{};
        EvilScene();
        virtual String getSceneId();
        virtual void dispose();
        virtual void load(Ref<DesktopDemoBase> amaJakk);
        virtual void render(Ref<RgbSurface> mmajkka, float n, float n2);
        virtual void handleMessage(String s, float n);
        static Ref<RgbSurface> AmAjAKk(Ref<IndexedSurface> maaakka, std::int32_t n, std::int32_t n2, std::int32_t n3,
                                       double n4);
        static Ref<HeightFieldMesh> aMaJakk(Ref<Camera> mmjjmkk, Ref<DesktopDemoBase> kmaamma);
        virtual void releaseReferences();
    };
    class LinjanenScene : public Scene {
      public:
        Ref<Camera> akKAMaJ{};
        Ref<SceneRenderer> AKKAMaJ{};
        Ref<RadialFlareMesh> aKKAMaJ{};
        Ref<WireframeMesh> AkkAMaJ{};
        Ref<RgbSurface> akkAMaJ{};
        Ref<DesktopDemoBase> AKkAMaJ{};
        Ref<ParticleCloudMesh> aKkAMaJ{};
        bool AkKamaJ{};
        float akKamaJ{};
        virtual String getSceneId();
        virtual void dispose();
        virtual void load(Ref<DesktopDemoBase> aKkAMaJ);
        virtual void render(Ref<RgbSurface> mmajkka, float majakKa, float n);
        virtual void handleMessage(String s, float n);
        LinjanenScene();
        virtual void releaseReferences();
    };
    class ByteReaders : public Object {
      public:
        static std::int32_t SIGNED_BYTE_BIAS;
        static Array<std::int32_t> UNSIGNED_BYTE_TABLE;
        ByteReaders();
        static std::int32_t readUnsignedByte(Array<std::int8_t> array, std::int32_t n);
        static std::int32_t readUnsignedShortLE(Array<std::int8_t> array, std::int32_t n);
        static std::int32_t readUnsignedShortBE(Array<std::int8_t> array, std::int32_t n);
        static std::int32_t readIntLE(Array<std::int8_t> array, std::int32_t n);
        static std::int32_t readSignedByte(Array<std::int8_t> array, std::int32_t n);
        static std::int32_t readSignedShortLE(Array<std::int8_t> array, std::int32_t n);
        static std::int32_t readSignedShortBE(Array<std::int8_t> array, std::int32_t n);
        static std::int32_t toUnsignedByte(std::int8_t b);
        static std::int32_t lowUnsignedByte(std::int32_t n);
        static void initialize_static();
        virtual void releaseReferences();
    };
    class Envelope : public Object {
      public:
        Array<std::int8_t> values{};
        std::int32_t sustainPosition{};
        std::int32_t loopStart{};
        std::int32_t loopEnd{};
        std::int32_t fadeoutStep{};
        bool enabled{};
        bool loopEnabled{};
        bool sustainEnabled{};
        Envelope(Array<std::int8_t> amAjAkk, std::int32_t amAjAkk2, std::int32_t amAjAkk3, std::int32_t amajAkk);
        Envelope(Array<Ref<Object>> array, std::int32_t n, std::int32_t n2, std::int32_t n3);
        virtual void setFadeoutStep(std::int32_t amajAkk);
        virtual std::int8_t valueAt(std::int32_t n);
        virtual std::int32_t advancePosition(std::int32_t n, bool b);
        virtual String toString();
        virtual void releaseReferences();
    };
    class EnvelopeCursor : public Object {
      public:
        Ref<Envelope> envelope{};
        std::int32_t position{};
        bool released{};
        bool enabled{};
        std::int32_t fadeoutLevel{};
        EnvelopeCursor();
        EnvelopeCursor(Ref<Envelope> majjkka);
        virtual void setEnvelope(Ref<Envelope> ajaKKAm);
        virtual void reset();
        virtual void release();
        virtual std::int8_t nextValue();
        virtual void releaseReferences();
    };
    class ModuleSample : public Object {
      public:
        static std::int8_t KKAmAja;
        static std::int8_t kKAmAja;
        static std::int8_t KkamAja;
        String kkamAja{};
        Array<std::int8_t> KKamAja{};
        std::int32_t kKamAja{};
        std::int32_t KkAMAja{};
        std::int32_t kkAMAja{};
        std::int32_t KKAMAja{};
        std::int8_t kKAMAja{};
        std::int32_t KkaMAja{};
        std::int32_t kkaMAja{};
        std::int32_t KKaMAja{};
        std::int32_t kKaMAja{};
        static std::int32_t KkAmaja;
        static std::int32_t kkAmaja;
        static std::int32_t KKAmaja;
        virtual std::int32_t KkaMAjA(std::int32_t n);
        static std::int32_t kKaMAjA(std::int32_t n);
        virtual void kKAMAjA(Array<std::int8_t> array, std::int32_t n, std::int32_t kKamAja);
        virtual void kKamAjA(String kkamAja);
        virtual void kkAMAjA(std::int32_t n, std::int32_t n2, std::int32_t n3);
        virtual void KKamAjA(std::int32_t kkAMAja);
        virtual void KKAMAjA(std::int32_t kkAMAja);
        virtual void KkAMAjA(std::int32_t kkamAja);
        virtual void KKaMAjA(std::int32_t kKaMAja);
        virtual std::int32_t kkaMAjA(Array<std::int32_t> array, std::int32_t i, std::int32_t n, std::int32_t n2,
                                     std::int32_t n3, std::int32_t n4, std::int32_t n5);
        ModuleSample();
        virtual void releaseReferences();
    };
    class ModuleInstrument : public Object {
      public:
        Array<Ref<Object>> sampleByNote{};
        Ref<Envelope> volumeEnvelope{};
        Ref<Envelope> panningEnvelope{};
        std::int32_t JAKKAMa{};
        std::int32_t jAKKAMa{};
        std::int32_t JakKAMa{};
        std::int32_t jakKAMa{};
        virtual void setSampleForAllNotes(Ref<ModuleSample> kmaamka);
        virtual void setSampleForNote(std::int32_t n, Ref<ModuleSample> kmaamka);
        ModuleInstrument();
        virtual void releaseReferences();
    };
    class ModulePattern : public Object {
      public:
        std::int32_t rowCount{};
        std::int32_t channelCount{};
        Array<Array<std::int8_t>> rows{};
        static std::int32_t NOTE_OFFSET;
        static std::int32_t INSTRUMENT_OFFSET;
        static std::int32_t VOLUME_OFFSET;
        static std::int32_t EFFECT_OFFSET;
        static std::int32_t EFFECT_PARAMETER_OFFSET;
        ModulePattern(std::int32_t akKaMaJ, std::int32_t akKaMaJ2);
        virtual void setCell(std::int32_t n, std::int32_t n2, std::int32_t n3, std::int32_t n4, std::int32_t n5,
                             std::int32_t n6, std::int32_t n7);
        virtual Array<std::int8_t> getRow(std::int32_t n);
        virtual void releaseReferences();
    };
    class ModuleSequencer : public Object {
      public:
        Array<std::int32_t> orderTable{};
        std::int32_t restartOrder{};
        Ref<ModuleSong> song{};
        bool repeatCurrentOrder{};
        std::int32_t orderIndex{};
        std::int32_t rowIndex{};
        virtual void setRestartOrder(std::int32_t maJakKa);
        virtual void setSong(Ref<ModuleSong> majakKa);
        virtual void loadOrderTable(Array<std::int8_t> array, std::int32_t n, std::int32_t n2);
        virtual void setRepeatCurrentOrder(bool majakKa);
        virtual void rewind();
        virtual void seekOrder(std::int32_t n);
        virtual void seekRow(std::int32_t n);
        virtual void advanceOrder();
        virtual Array<std::int8_t> nextRow();
        ModuleSequencer();
        virtual void releaseReferences();
    };
    class Mixable : public Object {
      public:
        virtual bool mix(Ref<MAD> p0, Array<std::int32_t> p1, std::int32_t p2, std::int32_t p3) = 0;
        virtual void releaseReferences();
    };
    class MixerBusListener : public Object {
      public:
        virtual void onMixerTick(Ref<MixerBus> p0) = 0;
        virtual void releaseReferences();
    };
    class ModuleVoice : public Mixable {
      public:
        Ref<ModuleSample> akkAMaj{};
        std::int32_t AKkAMaj{};
        std::int32_t aKkAMaj{};
        std::int32_t AkKamaj{};
        std::int32_t akKamaj{};
        std::int32_t AKKamaj{};
        std::int32_t aKKamaj{};
        std::int32_t Akkamaj{};
        std::int32_t akkamaj{};
        std::int32_t AKkamaj{};
        bool aKkamaj{};
        static std::int8_t AkKAmaj;
        static std::int8_t akKAmaj;
        static std::int8_t AKKAmaj;
        static std::int8_t aKKAmaj;
        static std::int8_t AkkAmaj;
        static std::int8_t akkAmaj;
        static std::int8_t AKkAmaj;
        static std::int8_t aKkAmaj;
        static std::int8_t AkKaMAj;
        static std::int8_t akKaMAj;
        static std::int8_t AKKaMAj;
        std::int8_t aKKaMAj{};
        std::int32_t AkkaMAj{};
        std::int32_t akkaMAj{};
        std::int32_t AKkaMAj{};
        std::int32_t aKkaMAj{};
        std::int32_t AkKAMAj{};
        std::int32_t akKAMAj{};
        std::int32_t AKKAMAj{};
        Array<std::int32_t> aKKAMAj{};
        std::int32_t AkkAMAj{};
        std::int32_t akkAMAj{};
        std::int32_t AKkAMAj{};
        std::int32_t aKkAMAj{};
        std::int32_t AkKamAj{};
        std::int32_t akKamAj{};
        std::int32_t AKKamAj{};
        std::int32_t aKKamAj{};
        std::int32_t AkkamAj{};
        std::int32_t akkamAj{};
        std::int32_t AKkamAj{};
        std::int32_t aKkamAj{};
        std::int32_t AkKAmAj{};
        static Array<std::int32_t> akKAmAj;
        static Array<std::int32_t> AKKAmAj;
        static Array<std::int32_t> aKKAmAj;
        virtual void kKaMAJa(bool aKkamaj);
        virtual void KkaMAJa(std::int32_t n);
        virtual void kkAmaJa(std::int32_t n);
        virtual void kKAmaJa(std::int32_t n);
        virtual void KKamaJa(std::int32_t n);
        virtual void KkAmaJa(std::int32_t n);
        virtual void kkamAJa(std::int32_t n);
        virtual void KKamAJa(std::int32_t n);
        virtual void kKAMAJa(std::int32_t n);
        virtual void kkamaJa(std::int32_t n);
        virtual void kkaMAJa(std::int32_t n);
        virtual void KKaMAJa(Ref<ModuleSample> kmaamka, std::int32_t n);
        virtual void KkamaJa(Ref<ModuleSample> akkAMaj, std::int32_t n, bool b);
        virtual void KkamAJa();
        virtual void KKAMAJa(bool b);
        virtual void kKamAJa(std::int32_t n, bool b);
        virtual void kkAMAJa();
        virtual void KKAmaJa();
        virtual void KkAMAJa(std::int32_t n);
        virtual bool mix(Ref<MAD> mad, Array<std::int32_t> array, std::int32_t n, std::int32_t n2);
        virtual void kKAmAJa(bool b);
        ModuleVoice();
        static void initialize_static();
        virtual void releaseReferences();
    };
    class ModuleChannel : public ModuleVoice {
      public:
        Ref<ModuleInstrument> amajAKk{};
        Ref<EnvelopeCursor> AMajAKk{};
        Ref<EnvelopeCursor> aMajAKk{};
        std::int32_t AmAJAKk{};
        std::int32_t amAJAKk{};
        std::int32_t AMAJAKk{};
        bool aMAJAKk{};
        ModuleChannel();
        virtual void AMaJAKk(Ref<ModuleInstrument> amajAKk, std::int32_t n);
        virtual void kkAMAJa();
        virtual void KKAmaJa();
        virtual void aMaJAKk();
        virtual std::int32_t amaJAKk();
        virtual void AmAjaKk();
        virtual void releaseReferences();
    };
    class MixerBus : public Mixable {
      public:
        Ref<Hashtable> MaJAKKA{};
        std::int32_t maJAKKA{};
        Ref<MixerBusListener> MAJAKKA{};
        float mAJAKKA{};
        float MajAKKA{};
        std::int64_t majAKKA{};
        MixerBus();
        virtual void MAjAkkA();
        virtual void mAjAkkA(Ref<MixerBusListener> majakka);
        virtual void MAJAkkA(float n);
        virtual void MaJaKKA(float majAKKA);
        virtual void MajAkkA(std::int32_t value, Ref<Mixable> value2);
        virtual void majAkkA(Ref<Mixable> value);
        virtual bool mix(Ref<MAD> mad, Array<std::int32_t> array, std::int32_t n, std::int32_t n2);
        virtual void mAJAkkA(Ref<MAD> mad, Array<std::int32_t> array, std::int32_t n, std::int32_t n2);
        virtual void releaseReferences();
    };
    class ModuleSong : public MixerBusListener {
      public:
        Ref<ModuleSequencer> MaJAkKa{};
        Array<Ref<Object>> maJAkKa{};
        Array<Ref<Object>> MAJAkKa{};
        Array<Ref<Object>> mAJAkKa{};
        std::int32_t MajAkKa{};
        std::int32_t majAkKa{};
        std::int32_t MAjAkKa{};
        String mAjAkKa{};
        Ref<ModulePattern> AmAjAkK{};
        std::int32_t amAjAkK{};
        std::int32_t AMAjAkK{};
        std::int32_t aMAjAkK{};
        Array<Ref<Object>> AmajAkK{};
        Ref<MixerBus> amajAkK{};
        Ref<ScriptEventScheduler> AMajAkK{};
        bool aMajAkK = false;
        Ref<SongPositionQueue> AmAJAkK = make_ref<SongPositionQueue>();
        virtual void JakkAMa(Ref<MixerBus> mmajmma2);
        virtual void JAKkAMa(Ref<ScriptEventScheduler> kmjakkk2);
        static float JAkkAMa(std::int32_t n);
        virtual void onMixerTick(Ref<MixerBus> mmajmma2);
        virtual Ref<ModuleInstrument> JaKKAMa(std::int32_t n);
        virtual void jAkkAMa(Array<std::int8_t> byArray);
        virtual void jaKkAMa(std::int32_t n, std::int64_t l);
        virtual std::int32_t jakkAMa(std::int32_t n);
        virtual bool JAKKAMa(std::int32_t n);
        virtual bool jaKKAMa(std::int32_t n, std::int32_t n2);
        virtual void jAKkAMa();
        ModuleSong();
        virtual void releaseReferences();
    };
    class ModuleLoader : public Object {
      public:
        static std::int32_t KKaMaJA;
        static Array<std::int32_t> kKaMaJA;
        ModuleLoader();
        static Ref<ModuleSong> kKAmAjA(Array<std::int8_t> array);
        static bool kkAmAjA(Array<std::int8_t> ascii);
        static bool KkamAjA(Array<std::int8_t> ascii);
        static Ref<ModuleSong> KKAmAjA(Array<std::int8_t> ascii);
        static Ref<ModuleSong> kkamAjA(Array<std::int8_t> ascii);
        static void initialize_static();
        virtual void releaseReferences();
    };
    class MovieBitReader : public Object {
      public:
        Array<std::int8_t> KAMaJAK{};
        std::int32_t kAMaJAK{};
        std::int32_t KamaJAK{};
        std::int32_t kamaJAK{};
        std::int32_t KAmaJAK{};
        MovieBitReader();
        virtual std::int32_t KAmAJak();
        virtual std::int32_t kamAJak();
        virtual std::int32_t kAMAJak();
        virtual void kaMAJak(Ref<MovieColorTransform> majjkmk);
        virtual std::int32_t KAMAJak();
        virtual Ref<MovieBounds> KaMajak();
        virtual Ref<MovieTransform> KaMAJak();
        virtual String KamAJak();
        virtual std::int32_t kAmaJak(std::int32_t n);
        virtual std::int32_t KAmaJak(std::int32_t n);
        virtual void kAmAJak(Array<std::int32_t> array, Array<std::int32_t> array2, bool b);
        virtual void releaseReferences();
    };
    class MovieBounds : public Object {
      public:
        std::int32_t minX{};
        std::int32_t minY{};
        std::int32_t maxX{};
        std::int32_t maxY{};
        MovieBounds();
        MovieBounds(Ref<MovieBounds> kaajmmk);
        MovieBounds(std::int32_t n, std::int32_t n2, std::int32_t n3, std::int32_t n4);
        virtual void includeBounds(Ref<MovieBounds> kaajmmk);
        virtual void includePoint(Ref<Point> point);
        virtual bool intersects(Ref<MovieBounds> kaajmmk);
        virtual bool contains(Ref<Point> point);
        virtual void releaseReferences();
    };
    class MovieTransform : public Object {
      public:
        std::int32_t ajakkAM{};
        std::int32_t AJakkAM{};
        std::int32_t aJakkAM{};
        std::int32_t AjAKkAM{};
        std::int32_t ajAKkAM{};
        std::int32_t AJAKkAM{};
        static Array<std::int32_t> aJAKkAM;
        MovieTransform();
        MovieTransform(Ref<MovieTransform> kmaammk);
        virtual void akKaMaj(Ref<Point> point, Ref<Point> point2);
        virtual void akkAmAJ(Ref<Point> point);
        virtual void aKKAmAJ(std::int32_t ajakkAM, std::int32_t ajAKkAM);
        virtual void AkkAmAJ(Ref<Point> point);
        virtual Ref<MovieBounds> AKKaMaj(Ref<MovieBounds> kaajmmk);
        virtual std::int32_t AKKAmAJ(std::int32_t n);
        virtual Ref<MovieTransform> AkkaMaj();
        static Ref<MovieTransform> aKKaMaj(Ref<MovieTransform> kmaammk, Ref<MovieTransform> kmaammk2);
        static std::int32_t AkKaMaj(std::int32_t n);
        static std::int32_t aKkAmAJ(std::int32_t n, std::int32_t n2);
        static std::int32_t AKkAmAJ(std::int32_t n, std::int32_t n2);
        static void initialize_static();
        virtual void releaseReferences();
    };
    class MovieColorTransform : public Object {
      public:
        std::int32_t kkAmaJa{};
        std::int32_t KKAmaJa{};
        std::int32_t kKAmaJa{};
        std::int32_t KkamaJa{};
        std::int32_t kkamaJa{};
        std::int32_t KKamaJa{};
        std::int32_t kKamaJa{};
        Array<std::int8_t> KkAMaJa{};
        Array<std::int8_t> kkAMaJa{};
        Array<std::int8_t> KKAMaJa{};
        Ref<MovieRasterizer> kKAMaJa{};
        MovieColorTransform(Ref<MovieRasterizer> kkaMaJa);
        static void KKAmAJA(std::int32_t n, std::int32_t n2, Array<std::int8_t> array);
        virtual void kkamAJA();
        virtual void KKamAJA(Array<std::int32_t> array, std::int32_t n);
        virtual std::int32_t KkamAJA(std::int32_t n);
        virtual void kKAmAJA(Ref<MovieFillStyle> kaaammk);
        virtual void kkAmAJA(Ref<MovieFillStyle> kaaammk);
        virtual void releaseReferences();
    };
    class MovieCharacter : public Object {
      public:
        Ref<MovieCharacter> aMAJakk{};
        Ref<MovieTimeline> AmaJakk{};
        std::int32_t amaJakk{};
        std::int32_t AMaJakk{};
        std::int32_t aMaJakk{};
        Ref<MovieBounds> AmAjAKk{};
        std::int32_t amAjAKk{};
        std::int32_t AMAjAKk{};
        Ref<Object> aMAjAKk{};
        MovieCharacter();
        virtual void releaseReferences();
    };
    class QuadraticEdge : public Object {
      public:
        std::int32_t aJaKkam{};
        std::int32_t AjAkKAm{};
        std::int32_t ajAkKAm{};
        std::int32_t AJAkKAm{};
        std::int32_t aJAkKAm{};
        std::int32_t AjakKAm{};
        bool ajakKAm{};
        QuadraticEdge();
        QuadraticEdge(Ref<QuadraticEdge> majjkkk);
        virtual void aKkAmaj(Ref<Point> point, Ref<Point> point2);
        virtual void aKKaMAj(Ref<Point> point, Ref<Point> point2, Ref<Point> point3);
        virtual Ref<QuadraticEdge> AKKaMAj(std::int32_t n);
        virtual std::int32_t AkKaMAj();
        virtual std::int32_t akKaMAj(Ref<Point> point, std::int32_t n);
        virtual void releaseReferences();
    };
    class MovieScanlineEdge : public QuadraticEdge {
      public:
        std::int32_t AJAkkAm{};
        std::int32_t aJAkkAm{};
        Ref<MovieScanlineEdge> AjakkAm{};
        Ref<MovieScanlineEdge> ajakkAm{};
        Ref<MovieFillStyle> AJakkAm{};
        Ref<MovieFillStyle> aJakkAm{};
        std::int32_t AjAKkAm{};
        std::int32_t ajAKkAm{};
        std::int32_t AJAKkAm{};
        std::int32_t aJAKkAm{};
        std::int32_t AjaKkAm{};
        std::int32_t ajaKkAm{};
        std::int32_t AJaKkAm{};
        std::int32_t aJaKkAm{};
        virtual void jaKKAmA(std::int32_t n);
        virtual void JaKKAmA(std::int32_t n);
        MovieScanlineEdge();
        virtual void releaseReferences();
    };
    class MovieFillStyle : public Object {
      public:
        Ref<MovieFillStyle> aJAkKam{};
        std::int32_t AjakKam{};
        std::int32_t ajakKam{};
        std::int32_t AJakKam{};
        bool aJakKam{};
        std::int8_t AjAKKam{};
        std::int64_t ajAKKam{};
        std::int32_t AJAKKam{};
        Ref<MovieTransform> aJAKKam{};
        Array<std::int32_t> AjaKKam{};
        Ref<MovieTransform> ajaKKam{};
        Ref<Object> AJaKKam{};
        Ref<MovieColorTransform> aJaKKam{};
        bool AjAkkam{};
        bool ajAkkam{};
        bool AJAkkam{};
        std::int32_t aJAkkam{};
        std::int32_t Ajakkam{};
        MovieFillStyle(Ref<MovieRasterizer> kaajkkk, std::int32_t ajakKam);
        MovieFillStyle(Ref<MovieRasterizer> kaajkkk, std::int32_t ajakKam, std::int32_t n, Array<std::int32_t> array,
                       Array<std::int32_t> array2, Ref<MovieTransform> kmaammk, Ref<MovieTransform> kmaammk2);
        virtual void AkKAMaj(Ref<MovieRasterizer> kaajkkk, std::int32_t ajakKam);
        virtual void releaseReferences();
    };
    class MovieDisplayObject : public Object {
      public:
        Ref<MovieRasterizer> MajaKka{};
        Ref<MovieDisplayObject> majaKka{};
        Ref<MovieCharacter> MAjaKka{};
        std::int32_t mAjaKka{};
        Ref<MovieTransform> MaJAKka{};
        Ref<MovieTransform> maJAKka{};
        Ref<MovieBounds> MAJAKka{};
        bool mAJAKka{};
        std::int32_t MajAKka{};
        Ref<MovieScanlineEdge> majAKka{};
        Ref<MovieColorTransform> MAjAKka{};
        MovieDisplayObject();
        virtual void jaKkaMA();
        virtual bool JaKkaMA(Ref<Point> point);
        virtual void releaseReferences();
    };
    class MovieFillSpan : public Object {
      public:
        Ref<MovieFillSpan> AjaKkAM{};
        std::int32_t ajaKkAM{};
        std::int32_t AJaKkAM{};
        Array<Ref<Object>> aJaKkAM{};
        std::int32_t AjAkKam{};
        bool ajAkKam{};
        bool AJAkKam{};
        virtual void aKkaMaj(Ref<MovieFillStyle> kaaammk);
        virtual std::int64_t akkaMaj(std::int32_t n, std::int32_t n2);
        virtual Ref<MovieFillSpan> AKkaMaj(Ref<MovieRasterizer> kaajkkk, std::int32_t n);
        MovieFillSpan();
        virtual void releaseReferences();
    };
    class MovieShapeDecoder : public MovieBitReader {
      public:
        Ref<MovieRasterizer> JaKKaMA{};
        Ref<MovieTimeline> jaKKaMA{};
        Ref<MovieColorTransform> JAKKaMA{};
        Ref<MovieTransform> jAKKaMA{};
        std::int32_t JakKaMA{};
        std::int32_t jakKaMA{};
        std::int32_t JAkKaMA{};
        Array<Ref<Object>> jAkKaMA{};
        Array<Ref<Object>> JaKkAma{};
        Array<std::int32_t> jaKkAma{};
        std::int32_t JAKkAma{};
        std::int32_t jAKkAma{};
        std::int32_t JakkAma{};
        std::int32_t jakkAma{};
        std::int32_t JAkkAma{};
        Ref<Point> jAkkAma{};
        Ref<Point> JaKKAma{};
        Ref<Point> jaKKAma{};
        Ref<Point> JAKKAma{};
        std::int32_t jAKKAma = 1;
        std::int32_t JakKAma = 2;
        std::int32_t jakKAma = 4;
        std::int32_t JAkKAma = 8;
        std::int32_t jAkKAma = 16;
        std::int32_t JaKkama = 128;
        bool jaKkama{};
        std::int32_t JAKkama{};
        Ref<MovieDisplayObject> jAKkama{};
        std::int32_t Jakkama{};
        Ref<MovieFillStyle> jakkama{};
        Ref<MovieFillStyle> JAkkama{};
        Ref<MovieFillStyle> jAkkama{};
        bool JaKKama{};
        std::int32_t jaKKama{};
        bool JAKKama{};
        std::int32_t jAKKama{};
        Ref<Point> JakKama{};
        Ref<Point> jakKama{};
        Ref<Point> JAkKama{};
        Ref<Point> jAkKama{};
        Ref<Point> JaKkAMa{};
        Ref<Point> jaKkAMa{};
        Ref<Point> JAKkAMa{};
        MovieShapeDecoder(Ref<MovieTimeline> jaKKaMA, std::int32_t kaMaJAK, Ref<MovieTransform> jakKaMA,
                          Ref<MovieColorTransform> jakKaMA2);
        virtual void akKamaJ(Ref<MovieFillStyle> kaaammk);
        virtual bool akKAmaJ();
        virtual std::int32_t akkamaJ(Ref<QuadraticEdge> majjkkk);
        virtual void AkKAmaJ(Ref<QuadraticEdge> majjkkk, bool b);
        virtual void AKkamaJ(bool b);
        virtual void aKkamaJ(Ref<Point> point, Ref<Point> point2);
        virtual void AkkamaJ(Ref<Point> point, Ref<Point> point2, Ref<Point> point3);
        static Ref<QuadraticEdge> AkkAmaJ(Ref<QuadraticEdge> majjkkk, Ref<Point> point, Ref<Point> point2);
        static Ref<QuadraticEdge> AKKamaJ(Ref<QuadraticEdge> majjkkk);
        virtual void aKkAmaJ(Ref<QuadraticEdge> majjkkk);
        virtual void AKkAmaJ(Ref<QuadraticEdge> majjkkk);
        virtual void akkAmaJ(Ref<QuadraticEdge> majjkkk);
        virtual void aKKamaJ(std::int32_t b, Ref<MovieFillStyle> jAkkama);
        virtual void aKKAmaJ(Ref<QuadraticEdge> majjkkk);
        virtual void AKKAmaJ();
        virtual void releaseReferences();
    };
    class MovieBitmap : public ImageConsumer {
      public:
        std::int32_t AMAjaKK{};
        std::int32_t aMAjaKK{};
        std::int32_t AmajaKK{};
        Array<std::int8_t> amajaKK{};
        Array<std::int32_t> AMajaKK_field{};
        Ref<ColorModel> aMajaKK_field{};
        Ref<MovieRasterizer> AmAJaKK_field{};
        bool amAJaKK_field{};
        bool AMAJaKK_field{};
        std::int32_t aMAJaKK_field{};
        Ref<ImageProducer> AmaJaKK_field{};
        static Array<Array<Array<std::int32_t>>> amaJaKK_field;
        static Array<std::int32_t> AMaJaKK_field;
        std::int32_t aMaJaKK_field{};
        Array<std::int32_t> AmAjAkk_field{};
        MovieBitmap(Ref<ImageProducer> amaJaKK, Ref<MovieRasterizer> amAJaKK);
        MovieBitmap(Ref<Image> image, Ref<MovieRasterizer> kaajkkk);
        MovieBitmap(Array<std::int32_t> aMajaKK, std::int32_t amAjaKK, std::int32_t amAjaKK2,
                    Ref<MovieRasterizer> amAJaKK);
        MovieBitmap(Array<std::int8_t> amajaKK, std::int32_t amAjaKK, std::int32_t amAjaKK2,
                    Ref<MovieRasterizer> amAJaKK);
        virtual void AMaJaKK();
        virtual void imageComplete(std::int32_t n);
        virtual void setColorModel(Ref<ColorModel> aMajaKK);
        virtual void setDimensions(std::int32_t amAjaKK, std::int32_t amAjaKK2);
        virtual void setHints(std::int32_t n);
        virtual void setPixels(std::int32_t n, std::int32_t n2, std::int32_t n3, std::int32_t n4,
                               Ref<ColorModel> colorModel, Array<std::int8_t> array, std::int32_t n5, std::int32_t n6);
        virtual void setPixels(std::int32_t n, std::int32_t n2, std::int32_t n3, std::int32_t n4,
                               Ref<ColorModel> colorModel, Array<std::int32_t> array, std::int32_t n5, std::int32_t n6);
        virtual void setProperties(Ref<Hashtable> hashtable);
        static void AmaJaKK();
        static std::int32_t aMaJaKK(std::int32_t n, std::int32_t n2);
        static std::int32_t amaJaKK(std::int32_t n, std::int32_t n2);
        virtual std::int32_t AmAjAkk(std::int32_t i, std::int32_t n, std::int32_t n2);
        virtual std::int32_t aMAJaKK(std::int32_t n, std::int32_t n2);
        virtual std::int32_t AMAJaKK(std::int32_t n, std::int32_t n2);
        virtual void aMajaKK(Ref<MovieFillStyle> kaaammk, Ref<Point> point, std::int32_t n, Array<std::int8_t> array,
                             std::int32_t n2);
        virtual void amAJaKK(Ref<MovieFillStyle> kaaammk, Ref<Point> point, std::int32_t n, Array<std::int32_t> array,
                             std::int32_t n2);
        virtual void AmAJaKK(Ref<MovieFillStyle> kaaammk, Ref<Point> point, std::int32_t n, Array<std::int32_t> array);
        virtual void AMajaKK(std::int32_t n, std::int32_t i, std::int32_t n2, Ref<MovieFillStyle> kaaammk);
        static void initialize_static();
        virtual void releaseReferences();
    };
    class MovieRasterizer : public ImageProducer {
      public:
        Ref<MovieTransform> MaJaKkA{};
        std::int32_t maJaKkA{};
        std::int32_t MAJaKkA{};
        bool mAJaKkA{};
        Ref<MovieBounds> MajaKkA{};
        Ref<MovieDisplayObject> majaKkA{};
        Ref<MoviePlayer> MAjaKkA{};
        Ref<MovieDisplayObject> mAjaKkA{};
        std::int32_t MaJAKkA{};
        std::int32_t maJAKkA{};
        bool MAJAKkA{};
        Ref<ColorModel> mAJAKkA{};
        std::int32_t MajAKkA{};
        std::int32_t majAKkA{};
        Ref<MovieBounds> MAjAKkA{};
        Ref<MovieBounds> mAjAKkA{};
        std::int32_t MaJakkA{};
        std::int32_t maJakkA{};
        Array<std::int8_t> MAJakkA{};
        Array<std::int32_t> mAJakkA{};
        std::int32_t MajakkA{};
        Ref<MovieFillStyle> majakkA{};
        Ref<MovieFillStyle> MAjakkA{};
        Array<Ref<Object>> mAjakkA{};
        std::int32_t MaJAkkA{};
        std::int32_t maJAkkA{};
        Array<Ref<Object>> MAJAkkA{};
        std::int32_t mAJAkkA{};
        std::int32_t MajAkkA{};
        std::int32_t majAkkA{};
        Ref<MovieFillSpan> MAjAkkA{};
        Ref<MovieFillSpan> mAjAkkA{};
        Ref<MovieFillSpan> MaJaKKA{};
        std::int64_t maJaKKA{};
        std::int32_t MAJaKKA{};
        std::int32_t mAJaKKA{};
        std::int32_t MajaKKA{};
        std::int32_t majaKKA{};
        std::int32_t MAjaKKA{};
        std::int32_t mAjaKKA{};
        std::int32_t MaJAKKA{};
        Array<std::int32_t> maJAKKA{};
        Array<std::int8_t> MAJAKKA{};
        std::int32_t mAJAKKA{};
        Array<std::int32_t> MajAKKA{};
        bool majAKKA{};
        Ref<ImageConsumer> MAjAKKA{};
        bool mAjAKKA{};
        MovieRasterizer(Ref<MoviePlayer> mAjaKkA);
        virtual void JAKKamA();
        virtual void JAkkAMA(Ref<MovieBounds> kaajmmk, bool maJaKkA, std::int32_t n, bool b);
        virtual void JAkkamA();
        virtual void jakkamA();
        virtual void JakkamA(std::int32_t maJaKkA, std::int32_t maJaKkA2);
        virtual void jAkkAMA(Ref<MovieCharacter> mAjaKka, std::int32_t mAjaKka2, Ref<MovieTransform> maJAKka,
                             Ref<MovieColorTransform> mAjAKka);
        virtual void jAKkAMA(std::int32_t n);
        virtual void JaKkAMA(Ref<MovieDisplayObject> kajakkk, std::int32_t majAKka);
        virtual bool jAkKamA(Ref<MovieDisplayObject> mAjaKkA, std::int32_t maJAKkA);
        virtual Ref<MovieDisplayObject> JakkAMA(std::int32_t n, std::int32_t n2);
        virtual bool jAKKamA(Ref<MovieDisplayObject> kajakkk, std::int32_t x, std::int32_t y);
        virtual void jakKamA(std::int64_t n, std::int32_t n2, std::int32_t maJaKKA, std::int32_t n3);
        virtual void JAKkamA(std::int32_t n, std::int32_t n2);
        virtual void jAKKAmA(std::int32_t jaKkAMa, std::int32_t jakkAMa, Ref<MovieFillStyle> kaaammk);
        virtual void jaKkAMA(std::int32_t majakkA);
        virtual void jAKkamA(Ref<MovieFillStyle> mAjakkA, std::int32_t n);
        virtual void jAkKAmA(std::int32_t n, std::int32_t n2);
        virtual void jaKkamA();
        virtual void JakKamA(Ref<MovieScanlineEdge> ajakkAm);
        virtual void JaKkamA();
        virtual void JAkKAmA();
        virtual void jakKAmA();
        virtual void JakKAmA();
        virtual std::int32_t jaKKamA(std::int32_t n);
        virtual std::int32_t JaKKamA(std::int32_t n);
        virtual std::int32_t JAKkAMA(std::int32_t n, std::int32_t n2);
        virtual void jAKKAMA(std::int32_t n, std::int32_t n2, std::int32_t n3);
        virtual void JAKKAmA();
        virtual bool jakkAMA(std::int32_t n, std::int32_t n2);
        virtual void jAkkamA(std::int32_t majAKkA, std::int32_t majAKkA2, Ref<ColorModel> majaKkA);
        virtual bool JAkKamA();
        virtual void jaKKAMA(Ref<MovieTimeline> kajamma, std::int32_t n);
        virtual std::int32_t JaKKAMA(Ref<MovieTimeline> kajamma, std::int32_t n);
        virtual void addConsumer(Ref<ImageConsumer> mAjAKKA);
        virtual bool isConsumer(Ref<ImageConsumer> imageConsumer);
        virtual void removeConsumer(Ref<ImageConsumer> imageConsumer);
        virtual void startProduction(Ref<ImageConsumer> imageConsumer);
        virtual void requestTopDownLeftRightResend(Ref<ImageConsumer> imageConsumer);
        virtual void JAKKAMA(bool b);
        virtual void releaseReferences();
    };
    class MovieTimeline : public MovieBitReader {
      public:
        std::int32_t Majakka{};
        std::int32_t majakka{};
        std::int32_t MAjakka{};
        std::int32_t mAjakka{};
        Ref<MovieBounds> MaJAkka{};
        std::int32_t maJAkka{};
        std::int32_t MAJAkka{};
        std::int32_t mAJAkka{};
        std::int32_t MajAkka{};
        std::int32_t majAkka{};
        Array<std::int8_t> MAjAkka{};
        bool mAjAkka{};
        bool MaJaKKa{};
        std::int32_t maJaKKa{};
        Ref<MovieSignal> MAJaKKa{};
        Ref<MovieRasterizer> mAJaKKa{};
        Ref<MoviePlayer> MajaKKa{};
        Array<std::int32_t> majaKKa{};
        std::int32_t MAjaKKa{};
        Array<Ref<Object>> mAjaKKa{};
        Ref<Object> MaJAKKa{};
        std::int32_t maJAKKa{};
        std::int32_t MAJAKKa{};
        bool mAJAKKa{};
        std::int32_t MajAKKa{};
        bool majAKKa{};
        bool MAjAKKa{};
        std::int32_t mAjAKKa{};
        std::int32_t MaJakKa{};
        std::int32_t maJakKa{};
        bool MAJakKa{};
        Ref<MovieBitReader> mAJakKa{};
        std::int32_t MajakKa{};
        std::int32_t majakKa{};
        static std::int32_t MAjakKa;
        std::int32_t mAjakKa_field{};
        std::int32_t MaJAkKa_field{};
        Ref<InputStream> maJAkKa_field{};
        bool MAJAkKa_field{};
        MovieTimeline(Ref<MoviePlayer> majaKKa, Ref<MovieRasterizer> maJaKKa);
        virtual bool AmAjakK();
        virtual std::int32_t aMAjAkK();
        virtual void amAjAkK(Ref<MovieDisplayObject> kajakkk, std::int32_t n);
        virtual void majAkKa(std::int32_t n);
        virtual std::int32_t AMAjAkK();
        virtual void MAJAkKa(std::int32_t maJakKa);
        virtual void MAjAkKa();
        virtual void MajAkKa();
        virtual void mAJAkKa();
        virtual void maJAkKa();
        virtual Ref<MovieCharacter> amaJAkK(std::int32_t n);
        virtual Ref<MovieCharacter> AmaJAkK(std::int32_t amaJakk);
        virtual void AMAjakK(std::int32_t n);
        virtual void mAjakKa();
        virtual void AmajakK();
        virtual void amAjakK();
        virtual void aMaJAkK();
        virtual void MaJAkKa(bool b);
        virtual void aMajAkK(std::int32_t n);
        virtual void aMAJAkK();
        virtual void AMAJAkK();
        virtual void AMajAkK();
        virtual void amajAkK(Array<std::int8_t> array, std::int32_t min);
        virtual std::int32_t aMAjakK();
        virtual void AmajAkK(std::int32_t n, std::int32_t n2);
        virtual std::int32_t AMaJAkK();
        virtual std::int32_t amAJAkK(std::int32_t n);
        virtual bool mAjAkKa(std::int32_t n);
        virtual void AmAjAkK(Ref<InputStream> maJAkKa);
        virtual void run();
        virtual std::int32_t AmAJAkK();
        virtual void releaseReferences();
    };
    class MovieSurfaceBridge : public Component {
      public:
        Ref<MoviePlayer> MAjAKka{};
        Ref<MovieController> mAjAKka{};
        Ref<RgbSurface> MaJakka{};
        Ref<ImageProducer> maJakka{};
        Array<std::int32_t> MAJakka{};
        std::int32_t mAJakka{};
        virtual void majakKa(std::int32_t n);
        virtual std::int32_t MajakKa();
        MovieSurfaceBridge(Ref<RgbSurface> maJakka, Ref<InputStream> inputStream);
        virtual Ref<Rectangle> bounds();
        virtual void update(Ref<Graphics> graphics);
        virtual void mAJakKa(Ref<Graphics> graphics);
        virtual void paint(Ref<Graphics> graphics);
        virtual void repaint();
        virtual bool isShowing();
        virtual Ref<Graphics> getGraphics();
        virtual Ref<Image> createImage(Ref<ImageProducer> maJakka);
        virtual void imageComplete(std::int32_t n);
        virtual void setColorModel(Ref<ColorModel> colorModel);
        virtual void setDimensions(std::int32_t maJakka, std::int32_t n);
        virtual void setHints(std::int32_t n);
        virtual void setPixels(std::int32_t n, std::int32_t n2, std::int32_t n3, std::int32_t n4,
                               Ref<ColorModel> colorModel, Array<std::int8_t> array, std::int32_t n5, std::int32_t n6);
        virtual void setPixels(std::int32_t n, std::int32_t n2, std::int32_t n3, std::int32_t n4,
                               Ref<ColorModel> colorModel, Array<std::int32_t> array, std::int32_t n5, std::int32_t n6);
        virtual void setProperties(Ref<Hashtable> hashtable);
        virtual void releaseReferences();
    };
    class MovieIntroScene : public Scene {
      public:
        Ref<MovieSurfaceBridge> amAjAKK{};
        Ref<RgbSurface> AMAjAKK{};
        Ref<RgbSurface> aMAjAKK{};
        Ref<RgbSurface> AmajAKK{};
        Ref<RgbSurface> amajAKK{};
        Ref<DesktopDemoBase> AMajAKK{};
        std::int32_t aMajAKK{};
        std::int32_t AmAJAKK{};
        MovieIntroScene();
        virtual String getSceneId();
        virtual void dispose();
        virtual void load(Ref<DesktopDemoBase> aMajAKK);
        virtual void render(Ref<RgbSurface> mmajkka, float n, float n2);
        virtual void handleMessage(String s, float n);
        virtual void releaseReferences();
    };
    class GraphicsRoutine : public Object {
      public:
        GraphicsRoutine();
        virtual String getRoutineId() = 0;
        virtual void load(Ref<DesktopDemoBase> kmaamma);
        virtual void enter();
        virtual void dispose();
        virtual void render(Ref<Graphics> graphics, float n, float n2);
        virtual void handleMessage(String s, float n);
        virtual void releaseReferences();
    };
    class EndscreenRoutine : public GraphicsRoutine {
      public:
        Ref<DesktopDemoBase> AkkAmAj{};
        Ref<Image> akkAmAj{};
        EndscreenRoutine();
        virtual String getRoutineId();
        virtual void load(Ref<DesktopDemoBase> akkAmAj);
        virtual void render(Ref<Graphics> graphics, float n, float n2);
        virtual void releaseReferences();
    };
    class SmoothedFrameTimer : public Object {
      public:
        std::int32_t sampleCount{};
        Array<std::int64_t> timestamps{};
        std::int64_t elapsedMillis{};
        std::int64_t originMillis{};
        std::int64_t initialFrameMillis{};
        SmoothedFrameTimer(std::int32_t n);
        SmoothedFrameTimer(std::int32_t n, std::int32_t kamAjak);
        virtual void reset();
        virtual void resetWithFrameDuration(std::int64_t kAmAjak);
        virtual std::int64_t getElapsedMillis();
        virtual void recordFrame();
        virtual float getAverageFrameMillis();
        virtual void releaseReferences();
    };
    class godog : public DesktopDemoBase {
      public:
        static Array<String> kAMajAk_field;
        static std::int32_t KamajAk_field;
        static std::int32_t kamajAk_field;
        static std::int32_t KAmajAk_field;
        static std::int32_t kAmajAk_field;
        Ref<StartupTunerCanvas> KaMAjAk_field{};
        Ref<Image> kaMAjAk_field{};
        Ref<Image> KAMAjAk_field{};
        static std::int32_t kAMAjAk_field;
        static std::int32_t KamAjAk_field;
        static bool kamAjAk_field;
        static std::int32_t KAmAjAk_field;
        static std::int32_t kAmAjAk;
        static bool KkAmAjA;
        bool kkAmAjA{};
        bool KKAmAjA{};
        Ref<LegacyFullscreenWindow> kKAmAjA{};
        Ref<MAD> KkamAjA{};
        Ref<MixerBus> kkamAjA{};
        Ref<ModuleSong> KKamAjA{};
        Ref<ModuleSong> kKamAjA{};
        Ref<ModuleSong> KkAMAjA{};
        bool kkAMAjA{};
        static Ref<RgbSurfacePresenter> KKAMAjA;
        static Ref<RgbSurface> kKAMAjA;
        static Ref<IndexedSurfacePresenter> KkaMAjA;
        static Ref<IndexedSurface> kkaMAjA;
        bool KKaMAjA{};
        std::int32_t kKaMAjA{};
        std::int32_t KkAmajA{};
        String kkAmajA{};
        Ref<Container> KKAmajA{};
        Ref<Hashtable> kKAmajA{};
        Ref<Hashtable> KkamajA{};
        std::int32_t kkamajA{};
        float KKamajA{};
        float kKamajA{};
        std::int32_t KkAMajA{};
        Ref<Hashtable> kkAMajA{};
        Ref<RgbSurface> KKAMajA{};
        Ref<RgbSurface> kKAMajA{};
        Ref<RgbSurface> KkaMajA{};
        Array<std::int32_t> kkaMajA{};
        Array<std::int32_t> KKaMajA{};
        Array<std::int32_t> kKaMajA{};
        static bool KkAmAJA;
        Ref<Graphics> kkAmAJA{};
        Ref<Graphics> KKAmAJA{};
        Ref<Component> kKAmAJA{};
        std::int32_t KkamAJA{};
        std::int32_t kkamAJA{};
        std::int32_t KKamAJA{};
        std::int32_t kKamAJA{};
        std::int32_t KkAMAJA{};
        std::int32_t kkAMAJA{};
        Ref<Font> KKAMAJA{};
        bool kKAMAJA{};
        static Ref<godog> KkaMAJA;
        Ref<Scene> kkaMAJA{};
        Ref<GraphicsRoutine> KKaMAJA{};
        std::int32_t kKaMAJA{};
        Ref<SmoothedFrameTimer> KkAmaJA{};
        float kkAmaJA{};
        float KKAmaJA{};
        float kKAmaJA{};
        float KkamaJA{};
        bool kkamaJA{};
        Array<String> KKamaJA{};
        virtual void kAMajAk();
        virtual void kamAJAk(Ref<ModuleSong> kkAMAjA, std::int32_t boost);
        virtual void kamajAk();
        virtual void KAMAjAk();
        virtual void KAmAJAk(String str);
        virtual void kAMAjAk(String str);
        virtual void KAMajAk(String str, String s);
        virtual void kaMAJAk(String str);
        virtual void KaMajAk(String str);
        virtual void KamAJAk(std::int32_t kkAMajA);
        virtual void kaMAjAk(Ref<Scene> value);
        virtual void KamajAk(Ref<GraphicsRoutine> value);
        virtual void kAMAJAk();
        godog();
        static void initialize_static();
        void renderFrame();
        virtual void releaseReferences();
    };
    void initialize_engine();
} // namespace godog
